### ISSUE TITLE
Register a Service Check does not work

### ISSUE THREAD

**Issue by vr255** [Icinga/icinga-powershell-framework#129]
I try to register a background Service Check for CPU utilization.
Unfortunately the background service does not calculate the average values for the specified time intervals.

What I have done and checked so far

I have checked that the Powershell Service is running
```
Get-Service -Name icingapowershell

Status   Name               DisplayName
------   ----               -----------
Running  icingapowershell   Icinga PowerShell Service
```
Then I registered the Deamon and created a new service.
```
Get-IcingaBackgroundDaemons

Name                           Value
----                           -----
Start-IcingaServiceCheckDaemon {}
```

```
Show-IcingaRegisteredServiceChecks;
[Notice]: Service Id: 5275219864641021224811420224776891459631192206
[Notice]:
Name                           Value
----                           -----
CheckCommand                   Invoke-IcingaCheckCPU
Interval                       30
Arguments
Id                             5275219864641021224811420224776891459631192206
TimeIndexes                    {1, 3, 5, 15}
```

I have also checked the permissions and restarted the service and the server.

```
Test-IcingaAgent
[Passed]: Icinga Agent service is installed
[Passed]: The specified user "NT AUTHORITY\NetworkService" is allowed to run as service
[Passed]: Directory "C:\ProgramData\icinga2\etc" is accessible and writeable by the Icinga Service User "NT AUTHORITY\NetworkService"
[Passed]: Directory "C:\ProgramData\icinga2\var" is accessible and writeable by the Icinga Service User "NT AUTHORITY\NetworkService"
[Passed]: Directory "C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\cache" is accessible and writeable by the Icinga Service User "NT AUTHORITY\NetworkService"
[Passed]: Icinga Agent configuration is valid
[Passed]: Icinga Agent debug log is disabled
```

The deamon edit the config file under:
C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\config

But the cache folder still remains empty
Am I still doing something wrong here or have I perhaps missed something?

Best regards

Viktor 

## Your Environment

* PowerShell Version used (`$PSVersionTable.PSVersion`):
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  3866
```

* Operating System and version (`Get-IcingaWindowsInformation Win32_OperatingSystem | Select-Object Version, BuildNumber, Caption`):
```
Version    BuildNumber Caption`
-------    ----------- --------
10.0.14393 14393
```

* Icinga Framework and Plugin version (`Get-Module -Name *icinga-powershell*`):
```

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.2.0      icinga-powershell-framework         {Get-IcingaCacheDir, Get-IcingaCustomPluginDir, Get-IcingaFrameworkRootPath, Get-IcingaPluginDir...}
Script     1.2.0      icinga-powershell-plugins           {Import-IcingaPlugins, Publish-IcingaPluginDocumentation, Use-IcingaPlugins}
```

**Comment by LordHepipud** [comment]
From the first view this should look fine. Is the service user for the `icingapowershell` service identical to the user the Icinga Agent is running with?
In case they are, this should work.

Does the Icinga Agent itself execute the checks properly?

**Comment by vr255** [comment]
As far as I can see, both services run under the same user

```
Get-WmiObject Win32_Service | ?{ $_.Name -like "*icinga*" } | ft Name,StartName

Name             StartName
----             ---------
icinga2          NT AUTHORITY\NetworkService
icingapowershell NT AUTHORITY\NetworkService
```

> Does the Icinga Agent itself execute the checks properly?

Yes

**Comment by LordHepipud** [comment]
This behaviour is interesting. Can you please try to stop the service and start the daemon within a PowerShell instance in foreground? For this an administrative shell is required

```powershell
Stop-Service icingapowershell;
Start-IcingaPowerShellDaemon;

# Lets access data we write into our cache
($Global:IcingaDaemonData.IcingaThreads).Keys;
$global:IcingaDaemonData.IcingaThreadPool;
$global:IcingaDaemonData.Config.BackgroundDaemon.RegisteredServices;
$global:IcingaDaemonData.BackgroundDaemon.ServiceCheckScheduler;
$global:IcingaDaemonData.BackgroundDaemon.ServiceCheckScheduler.'Invoke-IcingaCheckCPU';
```

Can you please share the output of the later commands? The last one

```powershell
$global:IcingaDaemonData.BackgroundDaemon.ServiceCheckScheduler.'Invoke-IcingaCheckCPU';
```

should fill with data over time depending on your interval (in your case 30 seconds, which means every 30 seconds additional data should be written into that).

Thank you in advance!

**Comment by vr255** [comment]
I executed the commands as requested and also waited about 30 minutes. But the last command doesn't return any values

```
($Global:IcingaDaemonData.IcingaThreads).Keys;

Icinga_PowerShell_ServiceCheck_Scheduler
Icinga_PowerShell_Background_Daemon
Icinga_Background_Service_Check_5275219864641021224811420224776891459631192206
```

```
$global:IcingaDaemonData.IcingaThreadPool;

Name                           Value
----                           -----
BackgroundPool                 System.Management.Automation.Runspaces.RunspacePool
ServiceCheckPool               System.Management.Automation.Runspaces.RunspacePool
```
```
$global:IcingaDaemonData.Config.BackgroundDaemon.RegisteredServices;

5275219864641021224811420224776891459631192206
----------------------------------------------
@{CheckCommand=Invoke-IcingaCheckCPU; Arguments=; Interval=30; TimeIndexes=System.Object[]}
```
```
$global:IcingaDaemonData.BackgroundDaemon.ServiceCheckScheduler;

Name                           Value
----                           -----
Invoke-IcingaCheckCPU          {average, results}
```
```
$global:IcingaDaemonData.BackgroundDaemon.ServiceCheckScheduler.'Invoke-IcingaCheckCPU';

Name                           Value
----                           -----
average                        {}
results                        {}
```

**Comment by LordHepipud** [comment]
Thank you for the test and providing the output. I run a test on a new Windows machine and can confirm the issue and reproduce it.
I'm still investigating on why the issue occures, tracked it how ever already done - the check commands are not executed and failing with an exception.

Once I know more I will update this issue.

**Comment by LordHepipud** [comment]
Did a long debug session and found the cause of the issue which was introduced with 1.2.0.

The master is already updated with a patch to resolve this issue. Sorry for the trouble!
