### ISSUE TITLE
Automatic update Windows Icinga2 Agent gives error if agent is already installed

### ISSUE THREAD

**Issue by matgenoux** [Icinga/icinga-powershell-framework#144]
I am using the Icinga Agent wizard to automatically install and update the agent on my Windows machines.
This works all fine however when I re-run my ansible playbook that has already the latest agent installed I get the following error

`[Error]: Failed to connect to your Icinga Director at "'https:// *****/icingaweb2/director/'". Please try again
Please re-enter your SelfService API Key for the Host-Template in case the key is no longer assigned to your host (Defaults: " jvfddvndjndndv****"):
`

Is there a possibility to avoid this error ?

## My Environment

* Icinga agent --2.12.1
* Icinga Director version 1.7.2
* Icinga PowerShell Framework 1.2.0
* Operating System and version: Windows 2012-2016-2019

**Comment by LordHepipud** [comment]
Hello and thank you for the issue.

Are you somehow removing the configuration file within the Icinga PowerShell Framework or dropping the host within Icinga?

This feature will connect to the Icinga Director and fetch a unique key which is later used for `authentication`. In case you are removing the config entry on the Icinga PowerShell Framework, you can't claim the host object again. In case you remove the host on the Icinga side and re-add it, you will have to drop the local stored Self-Service API key in addition with 

```powershell
Remove-IcingaDirectorSelfServiceKey

**Comment by matgenoux** [comment]
Hello and thank you for your answer.

In fact, I was removing the folder “Icinga-powershell-framework” before my deployment.
Because, I noticed that a new folder is created with the name of the version after each deploy:

`C:\Program Files\WindowsPowerShell\Modules`
```
icinga-powershell-framework
icinga-powershell-framework-1.2.0
etc...
```

Could you confirm that we have only this file is created :

`C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\config\config.json`

**Comment by LordHepipud** [comment]
Hello,

yes, this is the configuration file you have to keep. Inside is the API hey stored for the host object.
In addition you might consider keeping the cache directory as well, as some plugins like EventLog will store the last check execution time there to only fetch new log since the last run.

**Comment by matgenoux** [comment]
Thank you very much for your prompt answers.

The issue can be closed.

**Comment by LordHepipud** [comment]
You are welcome! Glad I was able to help 👍
