### ISSUE TITLE
Uninstall agent from powershell

### ISSUE THREAD

**Issue by mpr555** [Icinga/icinga-powershell-framework#148]
Please forgive me, but I have been looking through the docs to find out how to uninstall the Icinga agent through the framework.
Please could you point me in the right direction?

I have just switched from the icinga2agent module.

Kind regards,

Max

**Comment by LordHepipud** [comment]
Hello, thank you for the issue. The documentation is yet lacking some basic information which will be improved with the 1.3.0 release.

You can uninstall the Agent by using

```powershell
Uninstall-IcingaAgent;
```

If you wish to remove the data folder as well (including all certififactes and everathing else) you can run

```powershell
Uninstall-IcingaAgent -RemoveDataFolder;
```

I hope this helps!

**Comment by mpr555** [comment]
Perfect thanks!
