### ISSUE TITLE
Feature missing - NSClient

### ISSUE THREAD

**Issue by mpr555** [Icinga/icinga-powershell-framework#150]
With the deprecated PowerShell module icinga2agent, you were able to install NSClient with it.  Is this something that this framework supports?  If so, can you point me to the documentation?

Hoping to get this new framework installing the Icinga agent soon.  but at the moment  I can't get the service to start or connect.
 
Kind regards,

Max

**Comment by LordHepipud** [comment]
Hello and thank you for the issue. The NSClient++ is not supported by Icinga for Windows and we are not going to add addtional support there.
Our current strategy is to provide all mandatory plugins ourselfs and not rely on NSClient++, but the Icinga Agent for execution only.

In case the Icinga Agent can not be installed on certain systems, our strategy is to use [check_by_powershell](https://github.com/Icinga/check_by_powershell) which are currently developing.
