### ISSUE TITLE
Parameter -AddFirewallRule doesn't work

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icinga-powershell-framework#182]
When running the the Cmdlet Start-IcingaAgentInstallWizard there is no prompt if the firewall rule should be added. 
![image](https://user-images.githubusercontent.com/38723488/104056652-21bdff00-51f1-11eb-869f-a56f74e671bf.png)

If you add to the output the paramater "-AddFirewallRule 1" this will not processed like it should:
![image](https://user-images.githubusercontent.com/38723488/104056981-9d1fb080-51f1-11eb-9dac-fe8732c2ba76.png)

In result of this no firewall rules will be created

## Expected Behavior
1. there should be a prompt where the wizrd has ask if the firewall rules should be added
2. If the parameter is set, the firewall rules should be created

## Your Environment
Tested with W2012R2, W2016 and W2019
PS: 4.6 and 4.7
Icinga-PowerShell-Framework 1.3.0

**Comment by LordHepipud** [comment]
Hello and thank you for the report. Honestly this scenario is intended, as your configuration also does not accept connections from the master/satellite. Therefor there is no reason for opening port 5665 if the Agent is not accepting connections from a parent node.

This is a simple "security" feature to ensure ports are are not opened if not required.

**Comment by stevie-sy** [comment]
Hi and thanks for the input. 

I testet the wizard a little bit more with the new informations you wrote. It seems that the question „Is this Agent able to connect to its parent node(s)? (Y/n)“ from the wizard tips the scales. Depending on how you answer here, other questions appear or not. But without any deeper knowledge about everything this question maybe phrased in a somewhat ambiguous way. Because it was not evident (for us) that the answer to this question switches the parameter „—AcceptConnections“ on or off. My colleague and I are somehow missing the connection between the question and this parameter. 
Maybe the wording should look like the Linux Node Wizard? e.g. „Do you want to establish a connection to the parent node from this node? [Y/n]“ and also or alternatively the (additonal) questions „Accept config from parent node? [y/N]:“ and „Accept commands from parent node? [y/N]:“ should be asked in similar way. Then it could be clearer I think if the messages would be optimized for people who haven’t a deeper knowledge or use your Wizard the first time it would be very helpful.

Ok, If the question answer with „n“, I get the missing question about the firewall rule and also the question about the path for the CA-File. 
![image](https://user-images.githubusercontent.com/38723488/104342027-b464e380-54fa-11eb-9727-ec02aad1b9a9.png)

If the question is answered with "y", then only the question „Do you want to convert parent node(s) connection data to IP adresses? (Y/n)“ appears.  In our opinion, this question should always appear. Think about big networks, like we have, separated by routers, proxies, hardware firewalls, diffrent VLANs and also various DMZ etc. And for security reasons, e.g. the firewall admin only allows the IP connection on port 5665 between an agent (in diffent IP subnet, DMZ etc) and the parent node. And the admin also not allow any connection to the (interal) DNS. From the point of view of the question it is correct - both can communicate with each other - but not all network services work / are possible what might be needed.

What we also noticed when answering the question „Is this Agent able to connect to its parent node(s)? (Y/n)“, following question „Please specify the network destinations this Agent will connect to separated ....“ did not appear. If you do not want to run the installation immediately and therefore answer question „Do you want to run the installer now? (Otherwise only the configuration command will be printed) (Y/n)„ with "n" and copy the output to another server or your own automation tools, this can be problematic. Ok, you usually try that out beforehand. Because it fits, I wanted to have it mentioned.
![image](https://user-images.githubusercontent.com/38723488/104342091-c21a6900-54fa-11eb-9d62-50fecb13d40d.png)

Besides the wizard, of course we could create everything manully with the help of your docs. But here also some information and hints are missing (for us). For example there is no hint - neither in the documentation nor in the execution of the installation – that the parameters „—AcceptConnection“ and „—AddFirewallRule“ are somehow mutually exclusive or make no sense depending on the selected value. A hint somewhere like „because of choosing –AcceptConnection 1, we don’t create a Firewall rule“ for the reason you wrote. But without this, it’s irritating when you set „–AcceptConnection 1 –AddFirewallRule 1“ and then CmdLet writes „–AddFirewallRule 0“ as output during execution without reason. That could then be improved.

But what I also observed, that the uninstall routine doesn’t delete the firewall rule if created.

Anyway, in times of increasingly important and stricter security guidelines, the question arises as that Windows servers are not allowed to communicate with the Internet by default and the local firewall are switched on with the minimum of some base rules installed by Windows itself. Also when I think of our firewall admins, who first forbid everything and everything has to be explicitly enabled. With this point of view, should you always create the firewall rule for icinga or at least a hint?

**Comment by LordHepipud** [comment]
Thank you very much for the detailed input. My idea would be to not move forward with this and to not change the current behavior of `Start-IcingaAgentInstallWizard`.

We will work on a new entry point to install Icinga for Windows and will ship a new install function with v1.4.0. This will make things a lot easier, user friendly and intuitive then it is right now.

**Comment by LordHepipud** [comment]
Just to follow up on this (forgot to update the issue)

With Icinga for Windows v1.4.0 we added the Management Console as experimental feature:

```powershell
icinga -Manage
```

Maybe you can give it a try and check if it is more intuitive as the current wizard.

**Comment by stevie-sy** [comment]
Sadly this Cmdlet doenst work in our setup:
![image](https://user-images.githubusercontent.com/38723488/120178842-359ee780-c20a-11eb-8fb0-ba7fb5135e26.png)

**Comment by stevie-sy** [comment]
Same with the master from today (here called 1.5.0 because of versioning):
![image](https://user-images.githubusercontent.com/38723488/120182731-0f2f7b00-c20f-11eb-9129-326bf7aedf0d.png)

**Comment by LordHepipud** [comment]
This is interesting. Have you installed the Framework with PowerShell Gallery?
It looks like the issue occurs because the "root" path is not handled properly.

This looks like #237

**Comment by LordHepipud** [comment]
I just created PR #270, which should resolve this issue. Could you please update the folder 1.5.0 with the files from the fixed branch and test if everything is working? 
In case it does, it will be fixed with 1.5.0

**Comment by stevie-sy** [comment]
After the knowledge about the interactive mode from powershell I took some time to test the experimental manage function. 
First of all thank you for the retro feeling :-D. Because sometimes the menu is built up or the response to an input is slow. I felt like in times of i486 and DOS.  :-D.  But I think it have to to with the interactive mode on our servers. 

But joke aside: It looks good and would help a lot. Maybe a couple of comments:
* Question "Please enter your parent icinga zone": Here I get the the suggestion for the zone "master". 
![image](https://user-images.githubusercontent.com/38723488/126136056-ec4d47bc-c795-4e62-bd0a-ba5befd8dae5.png)
On the first views I overseen the [d] switch to delete and overwrite the suggested value. So I thought it isn't possible to change it. 
 
* Question "Please enter your parent icinga node name(s)": 
I think you should write the syntax or how I can put here the parent node names: List seperate with comma/semicolon, write one node and than enter and after the second one, etc. 
That this is the correct way was not also clear at first glance:
![image](https://user-images.githubusercontent.com/38723488/126144090-d0822fc5-b5ed-45c2-acb2-67039b14143c.png)
I think here should the question something like "please confirm". Because there are already two inputs:
![image](https://user-images.githubusercontent.com/38723488/126144395-c8beb9f9-7b91-4429-8a88-a96cfba61fb1.png)
Because it looks like you could enter a third one, what is incorrect: 
![image](https://user-images.githubusercontent.com/38723488/126144566-91340fac-5de4-4b3a-aa38-fdd66fe44d36.png)

*  Question "Please validate your configuration" - here is option "advanced" misleading. Because this option is always here. It doesn't matter if you are in the "base" or "advanced" mode. 
![image](https://user-images.githubusercontent.com/38723488/126145350-18e6a8bb-c691-457e-acee-2a0b6e4802d7.png)
![image](https://user-images.githubusercontent.com/38723488/126145454-ff66217f-82a9-4400-bb4d-516008f28b44.png)

* Change  location for Agent installagion package - Here I also overseen the d switch to delete and change the value like with the configuration for the parent zone

* Export/Installation - Here only a question: We used "Start-IcingaAgentInstallWizard" for installation. Should the Cmdlet "install-icinga" replace it?`

**Comment by LordHepipud** [comment]
Thank you for the input. Sometimes the loading is slow I agree - maybe I can find a way to speed certain things up, sadly the menu itself and everything is quite complex at the moment 😅

For the input handling: I will extend the help section for these categories to give a better understanding of what to expect.

Does the current [documentation](https://icinga.com/docs/icinga-for-windows/latest/doc/experimental/02-Management-Console/) would have helped in this matter? Besides on how to add multi values of course, which is missing I believe.

I will try to add a "Continue now" once every item is inside. I will have to get some ideas in addition on how I could look like, as I don't want to add too much information there, as obviously even right now certain things are missed.

For the advanced part:

Would you prefer `[a] Hide Advanced` or `[b] Basic Mode` (which would add another option I'm not happy about 😉

Agent installation:

I think that one is something what should be more present inside the documentation on how the menues itself work or by giving a short tutorial on how the CLI work. Not sure about this at the moment.

Last but not least - yes: `Install-Icinga` will replace `Start-IcingaAgentInstallWizard`. While we will support both ways for longer time, it will be preferred to use the new method as we will extend the functionality of Icinga for Windows with the next versions by alot.

The benefit of the menu structure is that you will no longer have to remember any commands, as the entire management can be done over the UI. Of course, using Cmdlets is still possible as before to automate as much as possible, but reduces the actual amounf of time to read documentations for example or to get starten.

I will post an update once I have a new version for the menues availlable. If you have additional feedback, please feel free to share it!

**Comment by stevie-sy** [comment]
docs:
I have to admit that I haven't read the linked documentation before  😄. But I read it now. Looks fine. If you include the hints from above, it would help a lot of people I think. 

advanced part:
Of course it would be better to have `[a] Hide Advanced` or `[b] Basic Mode`. But if this is too complicated to realize: Why not name it like `[a] switch between advanced/basic mode` and write it into the title of the menue? 

agent installation:
Thanks good to know, you replace `Start-IcingaAgentInstallWizard`. So will put this on our todo to change our automatation process. 
And I am completely with you, that this a big benefit about the UI. 

I'm really looking forward to your ideas and changes 🚀

**Comment by LordHepipud** [comment]
I made some changes now and the menu will switch from `[a] Advanced` to `[a] Hide Advanced`. In addition, `[h] Help` will toggle to `[h] Hide Help`

We also updated some texts and visuals so far and will even more improve this, while finishing 1.6.0

**Comment by stevie-sy** [comment]
Thanks I will test it

**Comment by stevie-sy** [comment]
I think testing is no longer necessary. Because I watched your live stream before. And it looks great what you showed us 😃

**Comment by LordHepipud** [comment]
Thank you very much ! I will close this issue then :)

v1.6.0 was released today.
