### ISSUE TITLE
Problem with "/" and "\" in Windows Paths

### ISSUE THREAD

**Issue by Nathaniel-Donahue** [Icinga/icinga-powershell-framework#186]
Hi
While Running "icinga> $ServiceData = Get-IcingaFrameworkServiceBinary" there pops up the following line: 
"Please enter the full path to your service binary repository:" and when I enter the path 
"C:\User\Administrator\Desktop\icinga-service-v1.0.0.zip" it doesn't work.

I expect it to work with forward and backward slashes e.g. "C:\User\Administrator\Desktop\icinga-service-v1.0.0.zip" and "C:/Users/Administrator/Desktop/icinga-service-v1.0.0.zip" 

When you enter the path with backward slashes it won't work and output an error.

**Comment by Yonas-net** [comment]
Hello Yonas, Thanks for the report. I have tested it and it works, but it would be better if you have the possibility to test it again with the referenced [PR](https://github.com/Icinga/icinga-powershell-framework/pull/187) Thank you.

**Comment by Yonas-net** [comment]
Hello @Nathaniel-Donahue, Thanks for the report. I have tested it and it works, but it would be better if you have the possibility to test it again with the referenced [PR](https://github.com/Icinga/icinga-powershell-framework/pull/187) Thank you.

**Comment by LordHepipud** [comment]
Thank you @Yonas-net . @Nathaniel-Donahue Please wait for the updated PR before testing it.
