### ISSUE TITLE
Add an option to flush the API director in IcingaAgentInstallWizard

### ISSUE THREAD

**Issue by lbetz** [Icinga/icinga-powershell-framework#190]
The old module (https://github.com/Icinga/icinga2-powershell-module/blob/master/doc/10-Basic-Arguments.md) has an option to flush the API directory for the agent installtion

-FlushApiDirectory (optional)

Would be fine to have it also in the current framework.

**Comment by LordHepipud** [comment]
Thank you for the feature request. The linked PR is now providing a Cmdlet to flush the API directory.
Do we really need it within the installer to flush the API directory (optional of course) or would it be enough to manually add the function call before/after the setup?

**Comment by LordHepipud** [comment]
Discussed offtopic: Only the Cmdlet is enough and is not required to be included inside the current wizard.
