### ISSUE TITLE
Cmdlet "Start-IcingaAgentInstallWizard" - Installation of the framework service doesn't work from local directory

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icinga-powershell-framework#191]
## Expected Behavior
For security reasons our many servers have no access to internet. They get their software from internal software chaches, repositories or software distribution points. So it should be possible to install the framework service also from a local or a network share like the icinga agent. 

## Current Behavior
While you can specify a (local) directory for the Icinga Agent during the installation wizard 
![image](https://user-images.githubusercontent.com/38723488/105351767-49e42f80-5bed-11eb-865d-919db22bd90a.png)
is this for the setup of the framework service not possible. It seems that the wizard and the parameter assumes that the installation source is always from a URL like GitHub or generally has access to the Internet:
![image](https://user-images.githubusercontent.com/38723488/105352060-b52e0180-5bed-11eb-91ea-2c1d334d6e9c.png)

![image](https://user-images.githubusercontent.com/38723488/105352572-5d43ca80-5bee-11eb-8d43-e4a49da9cfa2.png)

As you can see on the screenshots it doesn't matter if we answer the question with the path to the exe or to the zip file. 

In this case the workarround for the moment is to copy the exe into the target directory and install it manually with the commands from the docs:
![image](https://user-images.githubusercontent.com/38723488/105353202-3f2a9a00-5bef-11eb-98e3-ed651576aa3d.png)

Because the cmdlt "Get-IcingaFrameworkServiceBinary" has the same behavior.
![image](https://user-images.githubusercontent.com/38723488/105353174-35089b80-5bef-11eb-8972-a0284483616f.png)

## Your Environment

Tested with W2012R2, W2016 and W2019
PS: 4.6 and 4.7
Icinga-PowerShell-Framework 1.3.0

**Comment by LordHepipud** [comment]
Thank you for the report - this is already adressed in #186
A current workaround is to use / instead of \.

**Comment by stevie-sy** [comment]
Thanks I will try the workaround. And sorry that I've overseen the other issue.
