### ISSUE TITLE
Ignore SSL-Errors

### ISSUE THREAD

**Issue by KineticFox** [Icinga/icinga-powershell-framework#199]
Hello,

in the older/ [deprecated Version](https://github.com/Icinga/icinga2-powershell-module) you could set a flag to ignore SSL-Errors.
Is there a way you can do the same in this framework?

**Comment by LordHepipud** [comment]
Hello,

yes - you can do so by running the command `Enable-IcingaUntrustedCertificateValidation` before executing your commands.
This will disable certificate checks.

**Comment by KineticFox** [comment]
Ok thanks, that worked for me
