### ISSUE TITLE
Feature: Allow assignment of repositories to install Icinga Agent and Framework components from

### ISSUE THREAD

**Issue by LordHepipud** [Icinga/icinga-powershell-framework#221]
We should allow to define a "repository" to fetch Icinga Agent .msi installers and Framework Components from.
This would ensure to allow something like this:

```powershell
Install-IcingaAgent -Version 2.12.3
```

```powershell
Install-IcingaFrameworkComponent -Name 'plugins' -Release
```

but instead of using packages.icinga.com or github.com/icinga as package source, we could globally define

```
\\example.com\Icinga\windows
```

as base repository to get everything from.

**Comment by bieba** [comment]
This would be great.
Currently I am using a static repository URL which I am passing to the install command.


```
function Invoke-IcingaFrameworkPluginInstallation {
    Use-Icinga
    
    #ohne URL würde er immer die aktuellste Version laden
    Install-IcingaFrameworkComponent -Name plugins -Release -Url 'https://github.com/Icinga/icinga-powershell-plugins/archive/v1.3.1/v1.3.1.zip';
}

Export-ModuleMember -Function Invoke-IcingaFrameworkPluginInstallation
```
