### ISSUE TITLE
missing permission for event log queries triggers OK state

### ISSUE THREAD

**Issue by bieba** [Icinga/icinga-powershell-framework#226]
I want to check several event log sources.

## Expected Behavior
I want to check the security event log, e.g.
`Invoke-IcingaCheckEventlog -Warning 0 -Critical 0 -LogName Security -IncludeEventId 4769 -ExcludeEventId @() -IncludeUsername @() -ExcludeUsername @() -IncludeEntryType @() -ExcludeEntryType @() -IncludeMessage @() -ExcludeMessage @() -IncludeSource @() -ExcludeSource @() -Verbosity 2`
If something is found the result should be returned.

## Current Behavior
The query gets executed but it is aborted because of missing permissions.
But the plugin isn't either returning an error message back to Icinga nor a differant state than OK-State.

## Possible Solution
Return unknown state and transport the error message.

## Steps to Reproduce (for bugs)
```
**********************
Befehlsstartzeit: 20210312100848
**********************
PS>try { Use-Icinga; } catch { Write-Output 'The Icinga PowerShell Framework is either not installed on the system or not configured properly. Please check https://icinga.com/docs/windows for further details'; exit 3; }; Exit-IcingaPluginNotInstalled 'Invoke-IcingaCheckEventlog'; exit Invoke-IcingaCheckEventlog -Warning 0 -Critical 0 -LogName Security -IncludeEventId 4769 -ExcludeEventId @() -IncludeUsername @() -ExcludeUsername @() -IncludeEntryType @() -ExcludeEntryType @() -IncludeMessage @() -ExcludeMessage @() -IncludeSource @() -ExcludeSource @() -Verbosity 2

**********************
Befehlsstartzeit: 20210312100850
**********************
PS>TerminatingError(Get-EventLog): "Der angeforderte Registrierungszugriff ist unzulässig."
[OK] Check package "EventLog" (Match All)
\_ [OK] No EventLogs found: 0c
|
```

## Your Environment

* Icinga Plugins 1.31
* PowerShell Version used (`$PSVersionTable.PSVersion`):
```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.19170
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```
* Operating System and version (`Get-IcingaWindowsInformation Win32_OperatingSystem | Select-Object Version, BuildNumber, Caption`):
```
Version                                 BuildNumber                             Caption
-------                                 -----------                             -------
6.3.9600                                9600                                    Microsoft Windows Server 2012 R2 Dat...
```

**Comment by LordHepipud** [comment]
Does this issue still persist with Icinga for Windows 1.4.1, Plugins 1.4.0 and the new check configuration?
The new configuration will pass all check executions through a custom function `Exit-IcingaExecutePlugin` which will deal with any kind of exception which is not handled by the Framework, returning a proper formatted output message and `UNKNOWN`.

**Comment by bieba** [comment]
At the moment I am not able to update, probably in a few days. I will come back later.

**Comment by bieba** [comment]
I try to check this within this week.

**Comment by bieba** [comment]
Seems to work.

If I use a user (my normal windows login with admin credentials, but without high/admin privileges (run as admin)) without the required permissions it throws the following exception:
```powershell
[UNKNOWN]: Icinga Permission Error was thrown: CacheFolder: C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\cache

A plugin failed to write new data into the configured cache directory. Please update the permissions of this folder to allow write access for the user the Icinga Service is running with or use another folder as cache directory.
```
