### ISSUE TITLE
Some flags are ignored during icinga wizard reconfiguration

### ISSUE THREAD

**Issue by MikeKall** [Icinga/icinga-powershell-framework#231]
Ok so, I am trying for some time now to reconfigure Icinga agent silently using powershell but each time I run the command bellow the -SelfServiceApiKey flag and the -DirectorUrl flag I think that are skiped.
 
```
Start-IcingaAgentInstallWizard `
    -AllowUpdates 1 `
    -AllowVersionChanges 1 `
    -AddFirewallRule 1 `
    -AgentVersion $version `
    -SelfServiceAPIKey $selfserviceapikey `
    -UseDirectorSelfService 1 `
    -PackageSource $packagesource `
    -CAEndpoint $caendpoint `
    -EmptyCA 0 `
    -CAPort '5665' `
    -Endpoints $endpoints `
    -EndpointConnections $endpointconnections `
    -DirectorUrl "https://$($director)/icingaweb2/director/" `
    -OverrideDirectorVars 0 `
    -Ticket '' `
    -EmptyTicket 1 `
    -InstallFrameworkPlugins 0 `
    -InstallFrameworkService 0 `
    -ServiceUser 'NT Authority\SYSTEM' `
    -RunInstaller `
    -Reconfigure;
```

This is the message that it is being displayed each time I try to run a reconfiguration:
```
[Error]: The remote host for address "https://<hostname>/icingaweb2/director/self-service/powershell-parameters?key=382a2f4c6eb1c886c2b6c1ce4b024da00a187369" could not be resolved
[Error]: Failed to connect to your Icinga Director at "https://<hostname>/icingaweb2/director/". Please try again
Please re-enter your SelfService API Key for the Host-Template in case the key is no longer assigned to your host (Defaults: "382a2f4c6eb1c886c2b6c1ce4b024da00a187369"): 
```
When I copy and paste the exact same key and url in the above prompt it works fine.  

I have run the exact same command on a clean install (On a machine that never before had icinga configured) and it works fine.

## Expected Behavior

I think that there shouldn't be an error on these two flags

## Current Behavior

There is an error 

## Your Environment

* PowerShell Version used: 4.0
* Operating System: Microsoft Windows Server 2012 R2 Standard
* Icinga version: 2.12.3
* Framework version: 1.4.0
* Director version: 1.7.2

**Comment by LordHepipud** [comment]
Thank you for opening this issue. What happens if you delete the API key from the host inside the Icinga Director and run the command again?
I can't reproduce this issue on my test environment in this case.

Is the listed key `382a2f4c6eb1c886c2b6c1ce4b024da00a187369` the same one you ship with the argument? Because this key should not be used, as it should be overwritten by a local stored key.

If you run the setup once and run

```powershell
Show-IcingaDirecorSelfServiceKey
```

Do you receive a key or does it tell you no key is present? If no key is present, the Framework is unable to store the correct key for later usage.

**Comment by MikeKall** [comment]
Hi, thanks for your reply.

The steps that I follow to get this error is the following:

1. Clean install, configuration of the agent with the framework and deployment to the director.
2.  I then delete the host from the director.
3. Run the reconfiguration. I use the same script as in the first step and I just add the -Reconfigure flag.

> Is the listed key 382a2f4c6eb1c886c2b6c1ce4b024da00a187369 the same one you ship with the argument? 

No this is not the same key



> Do you receive a key or does it tell you no key is present?

I do receive a key but it's the one that it's displayed in the error, it's not the one that I am passing with the script

**Comment by LordHepipud** [comment]
After some testing I think I tracked down the problem. What happens if you run the same steps again, but before you run

```powershell
Remove-IcingaDirectorSelfServiceKey
```

Does this resolve the issue?

**Comment by MikeKall** [comment]
Yes It seems to be working! Thank you very much
Will this complication be resolved on a future update only with the reconfiguration flag?

**Comment by LordHepipud** [comment]
I'm confused on why this does not work out of the box for you. I tried it here within my test environment and it worked just fine.
If you are running 1.4.0 or later of the Framework, you can test the new `Management Console`:

```powershell
icinga -Manage
```

On the long term, this will be the new default for configurating everything. It would be helpful to give it a try and feedback if everything works as expected.

**Comment by MikeKall** [comment]
I have tested it on Windows 2016 Standard and Windows 2019 Standard too and I get the same results with the reconfiguration flag. So It might be a problem of some other people too.

**Comment by LordHepipud** [comment]
After more digging down I found the issue. Could you please test the linked PR and report back if the issue is now resolved?
What should happen is that you receive one error for the wrong/invalid key now, but the wizard should continue.

**Comment by MikeKall** [comment]
Hello @LordHepipud,

I tested the fix and it seems to work as expected!

**Comment by LordHepipud** [comment]
Thanks!
