### ISSUE TITLE
Exit-IcingaExecutePlugin throws exception for localized PerfCounters

### ISSUE THREAD

**Issue by Padahahn** [Icinga/icinga-powershell-framework#232]
Hey there,

After switching to invoke checks through the internal RestAPI, we noticed a problem with our german localized machines.
Our check looks something like this:

```
'C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe' -C {Use-Icinga -Minimal; $counterset = Get-Counter -ListSet 'Netzwerkschnittstelle' | Select-Object -ExpandProperty pathswithinstances | where {$_ -inotmatch 'isatap'}; Exit-IcingaExecutePlugin -Command Invoke-IcingaCheckPerfcounter -PerfCounter $counterset -Verbose 0}
```

Naturally, this outputs all perfcounters related to the NICs, excluding ISATAP.
But after executing the check, we are greeted with this exception:

```
[UNKNOWN] Check package "Performance Counter" - [UNKNOWN] \Netzwerkschnittstelle(Realtek PCIe GbE Family Controller)\Aktive TCP-Verbindungen f???r RSC: Ausnahme beim Aufrufen von "NextValue" mit 0 Argument(en):  "Der Leistungsindikator mit dem angegebenen Kategorienamen Netzwerkschnittstelle konnte nicht gefunden werden; Indikatorname Aktive TCP-Verbindungen f???r RSC.", \Netzwerkschnittstelle(Realtek PCIe GbE Family Controller)\Ausgabewarteschlangenl???nge: Ausnahme beim Aufrufen von "NextValue" mit 0 Argument(en):  "Der Leistungsindikator mit dem angegebenen Kategorienamen Netzwerkschnittstelle konnte nicht gefunden werden; Indikatorname Ausgabewarteschlangenl???nge.", \Netzwerkschnittstelle(Realtek PCIe GbE Family Controller)\TCP RSC: durchschnittliche Paketgr??????e: Ausnahme beim Aufrufen von "NextValue" mit 0 Argument(en):  "Der Leistungsindikator mit dem angegebenen Kategorienamen Netzwerkschnittstelle konnte nicht gefunden werden; Indikatorname TCP RSC: durchschnittliche Paketgr??????e.", \Netzwerkschnittstelle(Realtek PCIe GbE Family Controller)\TCP-RSC: zusammengef???gte Pakete/Sek.: Ausnahme beim Aufrufen von "NextValue" mit 0 Argument(en):  "Der Leistungsindikator mit dem angegebenen Kategorienamen Netzwerkschnittstelle konnte nicht gefunden werden; Indikatorname TCP-RSC: zusammengef???gte Pakete/Sek.."
\_ [UNKNOWN] \Netzwerkschnittstelle(Realtek PCIe GbE Family Controller)\Aktive TCP-Verbindungen f???r RSC: Ausnahme beim Aufrufen von "NextValue" mit 0 Argument(en):  "Der Leistungsindikator mit dem angegebenen Kategorienamen Netzwerkschnittstelle konnte nicht gefunden werden; Indikatorname Aktive TCP-Verbindungen f???r RSC."
\_ [UNKNOWN] \Netzwerkschnittstelle(Realtek PCIe GbE Family Controller)\Ausgabewarteschlangenl???nge: Ausnahme beim Aufrufen von "NextValue" mit 0 Argument(en):  "Der Leistungsindikator mit dem angegebenen Kategorienamen Netzwerkschnittstelle konnte nicht gefunden werden; Indikatorname Ausgabewarteschlangenl???nge."
\_ [UNKNOWN] \Netzwerkschnittstelle(Realtek PCIe GbE Family Controller)\TCP RSC: durchschnittliche Paketgr??????e: Ausnahme beim Aufrufen von "NextValue" mit 0 Argument(en):  "Der Leistungsindikator mit dem angegebenen Kategorienamen Netzwerkschnittstelle konnte nicht gefunden werden; Indikatorname TCP RSC: durchschnittliche Paketgr??????e."
\_ [UNKNOWN] \Netzwerkschnittstelle(Realtek PCIe GbE Family Controller)\TCP-RSC: zusammengef???gte Pakete/Sek.: Ausnahme beim Aufrufen von "NextValue" mit 0 Argument(en):  "Der Leistungsindikator mit dem angegebenen Kategorienamen Netzwerkschnittstelle konnte nicht gefunden werden; Indikatorname TCP-RSC: zusammengef???gte Pakete/Sek.."
```

As you might notice, there is an encoding problem, where e.g. "Paketgr??????e" should be "Paketgröße". Therefore, if the check is executed with the wrong perfcounter name it  won't find any values. Strangely, every 10th try or so, the check succeeds, followed by an exception the check after. 

When executing the check with a normal "exit" instead of "Exit-IcingaExecutePlugin", it works as expected so I looked a little deeper into the function.

Exit-IcingaExecutePlugin calls the function Invoke-IcingaInternalServiceCall, which itself invokes a webrequest at line 88.
I pulled the json conversion of the command arguments out of the webrequest and during the request, i converted it into utf8.
It now looks like this:

```
$CommandArgumentsJSON = ($CommandArguments | ConvertTo-Json -Depth 100);
$ApiResult = Invoke-WebRequest -Method POST -UseBasicParsing -Uri ([string]::Format('https://localhost:{0}/v1/checker?command={1}', $RestApiPort, $Command)) -Body ([System.Text.Encoding]::UTF8.GetBytes($CommandArgumentsJSON)) -ContentType 'application/json' -TimeoutSec $Timeout;
```
This might not be the best solution, but it certainly worked for me.

Curiously enough, blacklisting the command Invoke-IcingaCheckPerfcounter after whitelisting Invoke-IcingaCheck* doesn't seem to stop the execution over the RestAPI, but that might be a different issue.

## Expected Behavior

Executing a check over localized perfcounters through Exit-IcingaExecutePlugin should succeed.

## Current Behavior

Executing a check over localized perfcounters through Exit-IcingaExecutePlugin throws an exception because of encoding problems in the webrequest.

## Possible Solution

Converting the passed Arguments for the Checkcommand into UTF8 like:

```
$CommandArgumentsJSON = ($CommandArguments | ConvertTo-Json -Depth 100);
$ApiResult = Invoke-WebRequest -Method POST -UseBasicParsing -Uri ([string]::Format('https://localhost:{0}/v1/checker?command={1}', $RestApiPort, $Command)) -Body ([System.Text.Encoding]::UTF8.GetBytes($CommandArgumentsJSON)) -ContentType 'application/json' -TimeoutSec $Timeout;

```

## Steps to Reproduce (for bugs)

1. On a german localized machine, execute:  
```
'C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe' -C {Use-Icinga -Minimal; $counterset = Get-Counter -ListSet 'Netzwerkschnittstelle' | Select-Object -ExpandProperty pathswithinstances | where {$_ -inotmatch 'isatap'}; Exit-IcingaExecutePlugin -Command Invoke-IcingaCheckPerfcounter -PerfCounter $counterset -Verbose 0}
```
2. Exiting normally will execute the check locally with no errors:
```
'C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe' -C {Use-Icinga -Minimal; $counterset = Get-Counter -ListSet 'Netzwerkschnittstelle' | Select-Object -ExpandProperty pathswithinstances | where {$_ -inotmatch 'isatap'}; exit Invoke-IcingaCheckPerfcounter -PerfCounter $counterset -Verbose 0}
```

## Your Environment

* PowerShell Version used (`$PSVersionTable.PSVersion`):

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  610
```

* Operating System and version (`Get-IcingaWindowsInformation Win32_OperatingSystem | Select-Object Version, BuildNumber, Caption`):
```
Version    BuildNumber Caption
-------    ----------- -------
10.0.19042 19042       Microsoft Windows 10 Enterprise
```

**Comment by LordHepipud** [comment]
Thank you for the issue. You should not use `Get-Counter` or localised Performance Counters for check plugins.
The Framework provides a built-in functionallity to fetch the value of counters with the english name.

We added an entire section on how to work with Performance Counter on the Framework for this: [Developer Guide: Working with Performance Counters](https://icinga.com/docs/icinga-for-windows/latest/doc/developerguide/51-Working-with-Performance-Counters)

Does this resolve your problem?

**Comment by LordHepipud** [comment]
Could you please have a look on the linked PR and check if the issue is resolved now?

**Comment by LordHepipud** [comment]
Have you been able to test the linked PR and checked if this resolves the issue?

**Comment by Padahahn** [comment]
Sorry for the latent response.
I could in fact check the solution and it all works fine now.

Considering your comment on the creation of counters, I might have an understanding problem.
With your given instruction, I am creating a hashtable with PerfCounter:Value pairs locally, but how do I grab them and put the Values into my Icinga environment? 
I might have a fundemental misunderstanding of how this might work, but I need to define the counters that I want to check.  The whole *-IcingaPerformanceCounter* Cmdlets aren't part of the minimal framework, so I have to either use the full framework or define the counters, with get-counter. Or  I need to hardcode the counters by name, which isn't as dynamic as i would prefer.

I'm sorry if this is misplaced here. I'm fairly new to GitHub.

**Comment by LordHepipud** [comment]
Thank you for testing the fix and the feedback! I might have an understanding problem of what you might want to achieve.
Why not use the plugin we provide for monitoring Performance Counters: [Invoke-IcingaCheckPerfCounter](https://icinga.com/docs/icinga-for-windows/latest/plugins/doc/plugins/11-Invoke-IcingaCheckPerfcounter/)

**Comment by Padahahn** [comment]
OK, so I'm trying to be a bit more specific on what my goal is.

In my initial check I'm doing 3 things:

1.) Call the minimal framework:
```
Use-Icinga -Minimal;
```

2.) Build a list of performance counters which I want the values from:
```
$counterset = Get-Counter -ListSet 'Netzwerkschnittstelle' | Select-Object -ExpandProperty pathswithinstances | where {$_ -inotmatch 'isatap'};
```
3.) Invoke the check over the REST-API
```
Exit-IcingaExecutePlugin -Command Invoke-IcingaCheckPerfcounter -PerfCounter $counterset -Verbose 0}
```

As you can see, I am in fact using the provided Cmdlet "Invoke-IcingaCheckPerfcounter". As I can use specific counter names or a list of names on the switch "PerfCounter" I have decided to go with a prebuild list. 
Building this list into the variable counterset is shown in step 2. I like this appraoch, because of its dynamic nature. I also never found an appropriate solution excluding ISATAP-Adapters from the check. The only thing that bothers me, is that I have to be mindful of the localization of the system i am checking. But I think this is something I can eventually solve.
This adds about 1.5 seconds of execution time, ontop of the 7 seconds, loading the framework and executing the check itself takes.

I hope I got a bit clearer on what I am trying to accomplish with this.
