### ISSUE TITLE
the root module path always refers to the icinga-powershell-framework folder

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icinga-powershell-framework#237]
Hello, 

Every time I want to install a module (plugin,restapi,...) is the destination path C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\ 
and not C:\Program Files\WindowsPowerShell\Modules\

If i do:
# Use-Icinga;
# Install-IcingaFrameworkComponent -Name plugins -Release;
The destination path is C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\icinga-powershell-plugins 
and not C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins

Because of this I always have the following message:
Import-Module : The specified module 'icinga-powershell-plugins' was not loaded because no valid module file was found in any module directory.
At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\1.4.1\lib\core\framework\Install-IcingaFrameworkComponent.psm1:116 char:5
+     Import-Module $RepositoryName;
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (icinga-powershell-plugins:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
	

Also if i want to remove the framework:
# Uninstall-IcingaForWindows;
i have the error
[Notice]: The Icinga for Windows component "icinga-powershell-framework" at "C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\icinga-powershell-framework" could not ne found.
because the path is refer to icinga-powershell-framework in icinga-powershell-framework.

is it possible that the module root path is not correct when i use the command Install-IcingaFrameworkComponent or Uninstall-IcingaForWindows ? 

The version of powershell : 5.1.19041.906
Version of the framework is 1.4.1 (latest version)
Windows 10 Pro - 21H1

regards,
Geert

**Comment by LordHepipud** [comment]
Thank you for the report. This is a weird issue. The root folder should always refer to the `modules` folder and not the Framework itself.
How was the PowerShell Framework installed previously?

If you run

```powershell
Get-IcingaFrameworkRootPath
```

What is the result?

**Comment by gbin2265** [comment]
Hello,

PS C:\WINDOWS\system32> Get-IcingaFrameworkRootPath
C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\

At the very beginning with version 1.0 I did the installation manually.
Is there an ini file somewhere that keeps info/variables of the past?
I manually removed all the directories but still it continues to use this path.

regards,
Geert

**Comment by LordHepipud** [comment]
The module path is detected automatically by the module. Is the `.psm1` and `.psd1` file located in this location or are there and subdirectories under `C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\`?

Could you post a file list of this directory?

**Comment by gbin2265** [comment]
I do the installation from the Powershell Galery:
cd "C:\Program Files\WindowsPowerShell\Modules\"
Install-Module -Name icinga-powershell-framework;

This is the folder structure:

    Directory: C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework


Mode                 LastWriteTime         Length Name                                                                               
----                 -------------         ------ ----                                                                               
d-----          5/1/2021   2:19 PM                1.4.1                                                                              



    Directory: C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\1.4.1


Mode                 LastWriteTime         Length Name                                                                               
----                 -------------         ------ ----                                                                               
d-----          5/1/2021   2:19 PM                cache                                                                              
d-----          5/1/2021   2:19 PM                custom                                                                             
d-----          5/1/2021   2:19 PM                doc                                                                                
d-----          5/1/2021   2:19 PM                lib                                                                                
-a----         3/10/2021   7:28 AM           4003 icinga-powershell-framework.psd1                                                   
-a----         3/10/2021   7:28 AM          13549 icinga-powershell-framework.psm1                                                   
-a----         3/10/2021   7:28 AM           1063 LICENSE                                                                            
-a----         3/10/2021   7:28 AM           2130 PSScriptAnalyzerSettings.psd1                                                      
-a----         3/10/2021   7:28 AM           1654 README.md

**Comment by gbin2265** [comment]
Is subfolder 1.4.1 the problem?
This is created by the Install-Module.

**Comment by LordHepipud** [comment]
Ah, you installed the Framework by using PowerShell Gallery with `Install-Module`. Yes, this will cause issues then, as the root directory is different. You have to use `Install-Module` again to update and install all other components, as it is not supported to use both methods in parallel.

**Comment by gbin2265** [comment]
I have removed all the folders, i use ccleaner, reboot te windows and then reinstall everything .
Now he installs everything in the root of the modules.

Is het normal that there is always the version as folder before you see the psd1/psm1 ? 

PS C:\Program Files\WindowsPowerShell\Modules> icinga 
Import-LocalizedData : Cannot find the Windows PowerShell data file 'icinga-powershell-framework.psd1' in directory 'C:\Program 
Files\WindowsPowerShell\Modules\icinga-powershell-framework\icinga-powershell-framework\en-US\', or in any parent culture 
directories.
 
Import-LocalizedData : Cannot find the Windows PowerShell data file 'icinga-powershell-framework.psd1' in directory 'C:\Program 
Files\WindowsPowerShell\Modules\icinga-powershell-framework\icinga-powershell-framework\en-US\', or in any parent culture 
directories.
At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\1.4.1\lib\core\tools\Write-IcingaConsoleHeader.psm1:12

**Comment by LordHepipud** [comment]
The "problem" is that PowerShell Gallery seems to install everything in a version folder instead directly into `\modules`.
I will have a look on this and check if we can resolve that.

**Comment by LordHepipud** [comment]
In case you installed it with PowerShell Gallery at location `C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\`, could you please create a new folder `1.5.0` inside test the linked PR #270, by copying all files from this branch there?

This should fix the lookup and handling of all components.
