### ISSUE TITLE
Use-Icinga command takes too long to execute with system user

### ISSUE THREAD

**Issue by MikeKall** [Icinga/icinga-powershell-framework#244]
Hello,

I recently run into some problems with the `Use-Icinga` command. When I try to execute it it takes too much time.
I timed the execution with the `Measure-Command`:

```
Days              : 0
Hours             : 0
Minutes           : 4
Seconds           : 7
Milliseconds      : 420
Ticks             : 2474207152
TotalDays         : 0.00286366568518519
TotalHours        : 0.0687279764444444
TotalMinutes      : 4.12367858666667
TotalSeconds      : 247.4207152
TotalMilliseconds : 247420.7152
```
After the first execution it seems to be ok but the check on icinga times out during the 4-5 minutes. 
I run into the same problem on two more servers.

## Environments

OS: Windows Server 2012 R2 Standard
Powershell version: 4.0
Icinga version: 2.12.3
Icinga powershell framework version: 1.4.0

OS: Windows Server 2016 Standard
Powershell Version: 5.1
Icinga version: 2.12.3
Icinga powershell framework version: 1.4.0

**Comment by LordHepipud** [comment]
Hello and thank you for the issue.

Have you tried to [Enable Framework Code Caching](https://icinga.com/docs/icinga-for-windows/latest/doc/frameworkusage/05-Enable-Framework-Code-Caching/) on these machines?

In general this will boost the loading time on certain machines by 50-80%.

**Comment by MikeKall** [comment]
Yes that decreased the execution time to a minute. Thanks, but I think it still is a lot of time.
Do you may know why this happens to some machines?

**Comment by LordHepipud** [comment]
This can happen because of many different reasons, for example low CPU/Memory usage available, plenty of activity on the machines including huge disk I/O.

We added another experimental feature with 1.4.0 - [Experimental: Forward Checks to internal API](https://icinga.com/docs/icinga-for-windows/latest/doc/experimental/01-Forward-checks-to-internal-API/)

This will reduce the required Framework loading time even more and offload the checks to an internal API. Maybe this helps in addition on this machine.

Please note - it is still an experimental feature.

**Comment by MikeKall** [comment]
Hello @LordHepipud,

In my case it's not a resource issue since most of the machines have very little of their memory or CPU occupied.

I will test the feature you recommended!

**Comment by LordHepipud** [comment]
Hello,

do you have a feedback for me on how the new feature performs? Did you have time to test it already?

**Comment by MikeKall** [comment]
Hello,

No unfortunately I didn't have time to test the new feature but it is planned to be done.

**Comment by MikeKall** [comment]
Hello @LordHepipud,

I tested the new feature but I haven't seen any changes in the execution time compared to the `Code Caching`

**Comment by LordHepipud** [comment]
Hello

is this still an issue with the latest version of Icinga for Windows? We should have resolved this by now.
