### ISSUE TITLE
show-icingaeventloganalysis: unable to process a specific log

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-framework#246]
Hello,

I am testing the improved eventlog-check with the current framework-master. During my tests I used the new commandlet `show-icingaeventloganalysis` against various logs. One specific log can not be parsed.

## Expected Behavior

I was exepecting an output like this:
```
icinga> show-icingaeventloganalysis -logname Microsoft-Windows-Hyper-V-VMMS-Networking
[Notice]: Analysing EventLog "Microsoft-Windows-Hyper-V-VMMS-Networking"...
[Notice]: Logging Mode: Circular
[Notice]: Maximum Size: 0.00 GB
[Notice]: Current Entries: 6
[Notice]: Average Logs per Day: 6
[Notice]: Average Logs per Hour: 6
[Notice]: Average Logs per Minute: 6
[Notice]: Maximum Logs per Day: 6
[Notice]: Maximum Logs per Hour: 6
[Notice]: Maximum Logs per Minute: 6
[Notice]: Analysing Time: 0.26s
```

## Current Behavior
icinga> show-icingaeventloganalysis -logname Microsoft-Windows-Hyper-V-VMMS-Admin
```
[Notice]: Analysing EventLog "Microsoft-Windows-Hyper-V-VMMS-Admin"...
[Notice]: Logging Mode: Circular
[UNKNOWN]: Icinga Invalid Input Error was thrown: ConversionUnitMissing

Unable to parse input value. You have to add an unit to your input value. Example: "10GB". Allowed units are: "B, KB, MB, GB, TB, PB, KiB, MiB, GiB, TiB, PiB".
```

## Context
I always had the feeling, that microsoft somehow messed up this eventlog. Now I am sure :)
Its the only eventlog which is 2 times available in the gui, misplaced and so on.

![12-05-_2021_14-08-27](https://user-images.githubusercontent.com/34264690/117973032-27a52780-b32c-11eb-9267-0b8170bb5ab5.png)

![12-05-_2021_14-09-15](https://user-images.githubusercontent.com/34264690/117973041-2b38ae80-b32c-11eb-9efa-d0227ea5f07a.png)

A check against this eventlog is working.

## Your Environment

* PowerShell Version used (`$PSVersionTable.PSVersion`):

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  4402
```

* Operating System and version (`Get-IcingaWindowsInformation Win32_OperatingSystem | Select-Object Version, BuildNumber, Caption`):

```
Version    BuildNumber Caption
-------    ----------- -------
10.0.14393 14393       Microsoft Windows Server 2016 Datacenter
```

**Comment by LordHepipud** [comment]
Thank you for the issue. What happens if you use this command for this log:

```powershell
Get-WinEvent -ListLog 'Microsoft-Windows-Hyper-V-VMMS-Networking' -ErrorAction Stop;
```

Can you please share the output for this?

**Comment by K0nne** [comment]
The problematic eventlog ist listed 2 times :)

```
PS C:\WINDOWS\system32> Get-WinEvent -ListLog 'Microsoft-Windows-Hyper-V-VMMS-Admin' -ErrorAction Stop;

LogMode   MaximumSizeInBytes RecordCount LogName
-------   ------------------ ----------- -------
Circular           104857600       20446 Microsoft-Windows-Hyper-V-VMMS-Admin
Circular           104857600       20446 Microsoft-Windows-Hyper-V-VMMS-Admin
```

**Comment by LordHepipud** [comment]
Thanks. We will look on this on Friday.

**Comment by LordHepipud** [comment]
Can you please test the linked PR on this issue? This should resolve the problem with this command, while also adding the oldest and newest time stamp for the logs.

**Comment by K0nne** [comment]
Sorry. I am late to the party. The PR is working.  

```
PS C:\WINDOWS\system32> show-icingaeventloganalysis -logname Microsoft-Windows-Hyper-V-VMMS-Admin
[Notice]: Analysing EventLog "Microsoft-Windows-Hyper-V-VMMS-Admin"...
[Notice]: Logging Mode: Circular
[Notice]: Maximum Size: 0.10 GB
[Notice]: Current Entries: 20724
[Notice]: Average Logs per Day: 125
[Notice]: Average Logs per Hour: 79
[Notice]: Average Logs per Minute: 9
[Notice]: Maximum Logs per Day: 2605
[Notice]: Maximum Logs per Hour: 893
[Notice]: Maximum Logs per Minute: 245
[Notice]: Newest entry timestamp: 2021-05-28 21:24:23
[Notice]: Oldest entry timestamp: 2020-11-11 21:06:07
[Notice]: Analysing Time: 161.12s
```  

Thanks a lot!
