### ISSUE TITLE
Start-IcingaAgentInstallWizard fails at Get-IcingaUserSID.psm1

### ISSUE THREAD

**Issue by R-Sommer** [Icinga/icinga-powershell-framework#26]
Looks like #21 fixed it, but it doesn't.

## Expected Behavior
Start-IcingaAgentInstallWizard should install the framework

## Current Behavior
```
Method invocation failed because [System.Security.Principal.NTAccount] does not contain a method named 'New'.
At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\lib\core\tools\Get-IcingaUserSID.psm1:20
char:9
+         $NTUser       = [System.Security.Principal.NTAccount]::New($Domain, $Use ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MethodNotFound
```
## Steps to Reproduce (for bugs)
```
The wizard is complete. These are the configured settings:
========
-UseDirectorSelfService 1
-DirectorUrl http://192.168.53.210/icingaweb2/director/
-AddFirewallRule False
-CAFile ''
-EmptyCA 1
-InstallFrameworkPlugins 1
-PluginsUrl 'http://192.168.53.210/download/icinga-powershell-plugins.zip'
-InstallFrameworkService 1
-FrameworkServiceUrl 'http://192.168.53.210/download/icinga-service.zip'
-ServiceDirectory 'C:\Program Files\icinga-framework-service\'
-ServiceBin 'C:\Program Files\icinga-framework-service\icinga-service.exe'
-RunInstaller

========
Is this configuration correct? (Y/n):
Do you want to run the installer now? (Otherwise only the configuration command will be printed) (Y/n):
To execute your Icinga Agent installation based on your answers again on this or another machine, simply run this comman
d:
====
Start-IcingaAgentInstallWizard -UseDirectorSelfService 1 -DirectorUrl http://192.168.53.210/icingaweb2/director/ -AddFir
ewallRule False -CAFile '' -EmptyCA 1 -InstallFrameworkPlugins 1 -PluginsUrl 'http://192.168.53.210/download/icinga-powe
rshell-plugins.zip' -InstallFrameworkService 1 -FrameworkServiceUrl 'http://192.168.53.210/download/icinga-service.zip'
-ServiceDirectory 'C:\Program Files\icinga-framework-service\' -ServiceBin 'C:\Program Files\icinga-framework-service\ic
inga-service.exe' -RunInstaller
====
Downloading Icinga 2 Agent installer "Icinga2-v2.11.2-x86_64.msi" into temp directory "C:\Users\ADMINI~1\AppData\Local\T
emp\2\Icinga2-v2.11.2-x86_64.msi"
Installing new Icinga Agent version into "C:\Program Files\ICINGA2"
Icinga Agent was successfully installed
Successfully backed up Icinga 2 Agent default config
```

## Context
Logged in as local Administrator but not Domain-Admin (Logged in as Domain-Admin I run into other issue)

## Your Environment
* PowerShell Version used:
```
PS C:\Users\Administrator> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.19170
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

* Operating System and version:
```

PS C:\Users\Administrator> Get-WmiObject Win32_OperatingSystem | Select-Object Version, BuildNumber, Caption

Version                                 BuildNumber                             Caption
-------                                 -----------                             -------
6.3.9600                                9600                                    Microsoft Windows Server 2012 R2 Dat...
```

**Comment by NeverUsedID** [comment]
Do you use a released version or the current master? Check your C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\lib\core\tools\Get-IcingaUserSID.psm1. It looks like its the old one from the 1.0.0 RC.

**Comment by LordHepipud** [comment]
Based on the error output it seems you are on RC1 with the module. The bugfix is currently only available within the Snapshot (master). It will be fixed on the RC2 this / next week.

**Comment by R-Sommer** [comment]
I've used the master that why I wrote "Looks like #21 fixed it, but it doesn't."

**Comment by LordHepipud** [comment]
Could you please verify the file `Get-IcingaUserSID.psm1` in your modules folder `WindowsPowershell\modules\icinga-powershell-framework\lib\core\tools\`

The content should look like this: https://github.com/Icinga/icinga-powershell-framework/blob/master/lib/core/tools/Get-IcingaUserSID.psm1#L20

Your error messages states

```powershell
$NTUser       = [System.Security.Principal.NTAccount]::New($Domain, $Username);
```

which is the old function call. The new one should look like this

```powershell
$NTUser       = New-Object System.Security.Principal.NTAccount($Domain, $Username);
```

Is it possible that (maybe due to failed updates of the framework) two versions are installed right now and being crossloaded?

**Comment by R-Sommer** [comment]
>        $NTUser       = New-Object System.Security.Principal.NTAccount($Domain, $Username);

As already mentionend, it works if I run it as Domain-Admin. So I'd assume this is the root cause.

**Comment by NeverUsedID** [comment]
maybe you have an old module in your user module path.

**Comment by R-Sommer** [comment]
Don't think so.
![Search](https://user-images.githubusercontent.com/10089355/69863407-028a3980-129d-11ea-9272-4627fe282563.png)

**Comment by NeverUsedID** [comment]
I'am not sure, that the windows search shows you files from different users. I'am even not sure if Windows search shows files even when they are there. The errormessage clearly says that its executinng an old function. Maybe for some strange cahching like on temrinalservers a reboot is missing. I use https://www.voidtools.com/downloads/ to search all files and ignoring all permissions  on windows very fast (read: instant).

**Comment by R-Sommer** [comment]
I've rebooted this machine and the error disappeared. Closing this issue.
