### ISSUE TITLE
Invoke-IcingaCheckUpdates and Invoke-IcingaCheckCertificate fail to execute

### ISSUE THREAD

**Issue by MikeKall** [Icinga/icinga-powershell-framework#282]
Hello!

In some machines the `Invoke-IcingaCheckUpdates` and the `Invoke-IcingaCheckCertificate` commands return this message:

Example command usage:
`exit Invoke-IcingaCheckUpdates -Warning 5 -Critical 10`

```

Exception calling "WarnOutOfRange" with "1" argument(s): "Method invocation
failed because [System.Text.StringBuilder] does not contain a method named 

'New'."

At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\plugins

\Invoke-IcingaCheckUpdates.psm1:75 char:5

+     $IcingaCheck.WarnOutOfRange($Warning).CritOutOfRange($Critical) 

Out-Null;

+     

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException

    + FullyQualifiedErrorId : ScriptMethodRuntimeException

 

Exception calling "AddCheck" with "1" argument(s): "Exception calling 

"__SetCheckOutput" with "0" argument(s): "Method invocation failed because 

[System.Text.StringBuilder] does not contain a method named 'New'.""

At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\cache

\framework_cache.psm1:17420 char:5

+     $IcingaCheckPackage.AddCheck($Checks);

+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException

    + FullyQualifiedErrorId : ScriptMethodRuntimeException

 

Exception calling "Compile" with "0" argument(s): "Exception calling "Compile" 

with "0" argument(s): "Exception calling "__SetCheckState" with "1" 

argument(s): "Exception calling "__SetCheckOutput" with "0" argument(s): 

"Method invocation failed because [System.Text.StringBuilder] does not contain 

a method named 'New'.""""

At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\cache

\framework_cache.psm1:17458 char:16

+         return $IcingaCheckResult.Compile();

+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException

    + FullyQualifiedErrorId : ScriptMethodRuntimeException
```

I believe this started to happen after I updated the icinga powershell framework from 1.4.0 to 1.6.0

## Environment 
Icinga 2.12.3
Icinga powershell framework 1.6.0
Windows 2012 Standard R2

**Comment by LordHepipud** [comment]
Can you please test the linked PR for this? This should resolve the issue. Please also test it on systems which are currently working, just to ensure it is resolved entirely.

**Comment by MikeKall** [comment]
Sorry for the delayed response. 
I did test it in the Windows 2012 R2 servers and in a Windows 2016 server. 
It seem to be ok now

Thanks!

**Comment by Figment93** [comment]
Hi All, 

I am getting this same error when running the "Invoke-IcingaCheckCPU" command, only on one machine however. All devices are Windows 8.1 and all work except this one? 

`Exception calling "WarnOutOfRange" with "1" argument(s): "Method invocation
failed because [System.Text.StringBuilder] does not contain a method named 

'New'."

At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\plugins

\Invoke-IcingaCheckCPU.psm1:68 char:9

+         $IcingaCheck = (

+         ~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException

    + FullyQualifiedErrorId : ScriptMethodRuntimeException

 

Exception calling "Compile" with "0" argument(s): "Exception calling "Compile" 

with "0" argument(s): "Exception calling "__SetCheckState" with "1" 

argument(s): "Exception calling "__SetCheckOutput" with "0" argument(s): 

"Method invocation failed because [System.Text.StringBuilder] does not contain 

a method named 'New'.""""

At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\lib\i

cinga\plugin\New-IcingaCheckResult.psm1:34 char:16

+         return $IcingaCheckResult.Compile();

+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException

    + FullyQualifiedErrorId : ScriptMethodRuntimeException
`

**Comment by LordHepipud** [comment]
Hello,

thank you for your message, This is already fixed in the linked PR and will be released with 1.5.1 soon. We are still trying to collect more feedback in case anything else pops up.

**Comment by Figment93** [comment]
Thanks @LordHepipud! I'll await the update and update on the next release.

**Comment by wrkhunte** [comment]
> Thanks @LordHepipud! I'll await the update and update on the next release.

did it work for you? I am using the Powershell Plugins 1.5.1 and have the above mentioned problems on several fully patched servers with Windows Server 2012 R2. This applies to every tested plugin, e.g. IcingaCheckMemory and IcingaCheckCPU

**Comment by Figment93** [comment]
> > Thanks @LordHepipud! I'll await the update and update on the next release.
> 
> did it work for you? I am using the Powershell Plugins 1.5.1 and have the above mentioned problems on several fully patched servers with Windows Server 2012 R2. This applies to every tested plugin, e.g. IcingaCheckMemory and IcingaCheckCPU

Hi @wrkhunte yes, I just went in and edited the two files as detailed in the[ bug fix ](https://github.com/Icinga/icinga-powershell-framework/pull/283/commits/7039cec560908f59ef80a07d415c7f3cf5e2a262)

- lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1 
- lib/icinga/plugin/New-IcingaCheckPackage.psm1

**Comment by wrkhunte** [comment]
> > > Thanks @LordHepipud! I'll await the update and update on the next release.
> > 
> > 
> > did it work for you? I am using the Powershell Plugins 1.5.1 and have the above mentioned problems on several fully patched servers with Windows Server 2012 R2. This applies to every tested plugin, e.g. IcingaCheckMemory and IcingaCheckCPU
> 
> Hi @wrkhunte yes, I just went in and edited the two files as detailed in the[ bug fix ](https://github.com/Icinga/icinga-powershell-framework/pull/283/commits/7039cec560908f59ef80a07d415c7f3cf5e2a262)
> 
> * lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
> * lib/icinga/plugin/New-IcingaCheckPackage.psm1

ah okay thanks for the feedback. i realized it was my mistake. After the update I forgot to open a new Powershell to reload the icinga plugins.
