### ISSUE TITLE
Typo in output of Get-IcingaAgentInstallation and Get-IcingaAgentVersion - mayor vs. major

### ISSUE THREAD

**Issue by 408573** [Icinga/icinga-powershell-framework#291]
---

We've spent some time evaluating why some if conditions regarding the installed Icinga Agent didn't work.
It came down to a typo of the version variable "mayor" which wasn't obvious at first (should be "major" (with "j").
Maybe one can correct the output, knowing that already implemented evaluations out there would break.
Also irritating was the variable name "fixes" which we've expected to be "build".
Thanks for checking!

## Expected Behavior
When calling Get-IcingaAgentInstallation or Get-IcingaAgentVersion return the following attributes as in other software projects.
* major
* minor
* build 

## Current Behavior
When calling Get-IcingaAgentInstallation or Get-IcingaAgentVersion return the following attributes:
```
PS C:\WINDOWS\system32> Get-IcingaAgentVersion
Name                           Value
----                           -----
Snapshot
Minor                          12
Full                           2.12.2
Mayor                          2
Fixes                          2
```
```
PS C:\WINDOWS\system32> (Get-IcingaAgentInstallation).version

Name                           Value
----                           -----
Snapshot
Minor                          12
Full                           2.12.2
Mayor                          2
Fixes                          2
```
## Possible Solution
Correct the typo from "mayor" to "major".

## Steps to Reproduce (for bugs)
1. run the above mentioned commands Get-IcingaAgentInstallation or Get-IcingaAgentVersion

## Context
We're using the version of the installed Icinga2 Agent to evatluate whether an update of the Icinga2 Agent is necessary or not. 

## Your Environment
* PowerShell Version used (`$PSVersionTable.PSVersion`):
  * 5.1.14409.1018
  * 5.1.14393 .3866
* Operating System and version (`Get-IcingaWindowsInformation Win32_OperatingSystem | Select-Object Version, BuildNumber, Caption`): 
   * 6.3.9600 / 9600 / Microsoft Windows Server 2012 R2 Standard
   * 10.0.14393 / 14393 / Microsoft Windows Server 2016 Datacenter

**Comment by LordHepipud** [comment]
Thank you for the issue. Yes, this is something we can resolve and fix for all occurrences in our code.
