### ISSUE TITLE
Setting a host display name (display_name) when using IcingaAgentInstallWizard not possible

### ISSUE THREAD

**Issue by 408573** [Icinga/icinga-powershell-framework#292]
---

We didn't find out how to set the host display_name to the local part (i.e. without the domain part) when using _Start-IcingaAgentInstallWizard @AgentInstallParams -RunInstaller_.
See also:
* https://community.icinga.com/t/icinga-powershell-framework-using-hostname-as-display-name-without-domain/6074
* https://community.icinga.com/t/self-service-api-display-name/7593

## Expected Behavior
There should be a parameter for the host display name (display_name) to be set during registring of a new host with Icinga Director.
With the old PowerShell Module a display name was automatically set to the hostname (local part, without the domain part). All that without defining  something manually.

## Current Behavior
There is no known option / parameter to define a display name in Icinga Director while registring via _Start-IcingaAgentInstallWizard_.

## Possible Solution
Make a parameter available to set _display_name_ when registring with Icinga Director.

## Steps to Reproduce (for bugs)
Install Icinga2 Agent with PowerShell Framework using _Start-IcingaAgentInstallWizard_ 
```
AgentInstallParams = @{
			"SelfServiceAPIKey" = $SelfServiceAPIKey;
			"UseDirectorSelfService" = 1;
			"lowercase" = 1;
			"DirectorUrl" = 'http://icingamaster1.domain.net/icingaweb2/director';
			"OverrideDirectorVars" = 0;
			"ConvertEndpointIPConfig" = 0;
			"CAEndpoint" = "icingamaster1.domain.net";
			"CAPort" = 5665;
			"Ticket" = '';
			"EmptyTicket" = 1;
			"AgentVersion" = $appVersion;
			"Endpoints" = $ParentEndpoints;
			"ParentZone"  = $ParentZone;
			"AllowVersionChanges" = 1;
			"InstallFrameworkPlugins" = 1;
			"InstallFrameworkService" = 0;
			"PluginsUrl" = "$dirFiles\icinga-powershell-plugins-1.3.0.zip";
			"PackageSource" = "$dirFiles";
			"ServiceUser" = "LocalSystem"
			}
	 
	Start-IcingaAgentInstallWizard @AgentInstallParams -RunInstaller
```

## Your Environment
* PowerShell Version used (`$PSVersionTable.PSVersion`):
  * 5.1.14409.1018
  * 5.1.14393 .3866
* Operating System and version (`Get-IcingaWindowsInformation Win32_OperatingSystem | Select-Object Version, BuildNumber, Caption`): 
   * 6.3.9600 / 9600 / Microsoft Windows Server 2012 R2 Standard
   * 10.0.14393 / 14393 / Microsoft Windows Server 2016 Datacenter
* Icinga2 Version 2.12.2-1 (HA)
* Icinga Web 2 Version 2.8.2
* Icinga Director Version 1.8.0

**Comment by LordHepipud** [comment]
Thank you for your issue. Right now, the display_name is no longer set as in our experience most users had different tasks running in addition, to automatically set the display_name.

In case the Director integration part run multiple times, it had always overwritten the "properly" set name with the one transported over the self service API.

https://github.com/Icinga/icinga-powershell-framework/blob/master/lib/apis/Register-IcingaDirectorSelfServiceHost.psm1#L65

To enhance this, we would have to update above's code to ship the `display_name` and set it to another value.

I will add this to the v1.6.0 milestone as feature.
