### ISSUE TITLE
IcingaCheckPerfCounter - ThresholdInterval not working properly?

### ISSUE THREAD

**Issue by DeHook** [Icinga/icinga-powershell-framework#295]
Hi,
we tested the IcingaCheckPerfCounter Powershell Check and we want to use the ThresholdInterval option for average values of the last x minutes.

We installed the icingapowershell Service on the Server and registered the Check.

When we open the performance monitor and run the check simultaniously, the average values will not fit.

I don't know where our mistake is and where we can change the query.

The Check-query is `Invoke-IcingaCheckPerfCounter -PerfCounter '\processor(0)\% processor time' -ThresholdInterval 1m`

![thi](https://user-images.githubusercontent.com/25317879/123750997-8102ef00-d8b7-11eb-977d-205bbce01103.JPG)

Thank you.

**Comment by LordHepipud** [comment]
Can you please test the linked PR if this resolves the issue?

For testing:

1. Stop the background daemon service
2. Update the Framework
3. Remove the `Invoke-IcingaCheckPerfCounter` json files within the cache folder for both, `checkresult` and `checkresult_store`
4. Restart the background daemon service
5. Wait for the files to be written on your disk in the folder
6. Execute the plugin again within a new PowerShell session

After that, it should work. I will add this fix to v1.5.1 if you report back successfully.

Thank you again!

**Comment by DeHook** [comment]
I have a few questions.
We updated the two files in the lib folder. We reviewed registered checks and restarted the icingapowershell service. This looks OK.
We are waiting for the cache files more than 60 minutes and they aren't created yet. I don't know what we did wrong or why the cache files aren't there now.

The `-ThresholdInterval`-parameter will not be automatically detected in the powershell console when I begin to write the parameter and use the tabulator. Is this normal for this check?

**Comment by LordHepipud** [comment]
Is the background daemon registered? You can check this with

```

**Comment by DeHook** [comment]
Okay, it's working now! Thank you very much. 
The Background Daemon were not running and the permissions to the cache folder were not set. 

I tested it with a few other counters and it's working fine.

![02](https://user-images.githubusercontent.com/25317879/124120308-eb608e80-da73-11eb-88bf-c323c4c414bc.JPG)

**Comment by LordHepipud** [comment]
Excellent, thank you very much! Just one important thing:

In case you are using the identical plugin, in this case `Invoke-IcingaCheckPerfCounter`, please ensure you only register **one** check command definition and add all required Performance Counters as list to `-PerfCounter`.

Otherwise they might conflict each other.

Basically your registered service check should cover with `processor`, `memory` and even more directly with `-PerfCounter`.

I will apply the fix directly to v1.5.1.
