### ISSUE TITLE
Microsoft Vulnerability with icinga-service.

### ISSUE THREAD

**Issue by drapiti** [Icinga/icinga-powershell-framework#298]
Our security department has identitified a potential vulnerbility with the default installation of the icingapowershell service.

"The remote Windows host has at least one service installed that uses an unquoted service path, which contains at least one whitespace. A local attacker can gain elevated privileges by inserting an executable file in the path of the affected service."

The second part is ok, it's the first part which should be quoted. 

![image](https://user-images.githubusercontent.com/4235359/124944692-d359b380-e00d-11eb-99b4-a0bcae810bf6.png)

Cheers.

**Comment by LordHepipud** [comment]
Thank you for the report. We just provided a fix with the linked PR and published 1.5.2 to fix this.
We have also backported the fix to 1.3.2 and 1.4.2.

In addition we provided a [knowledge base entry](https://icinga.com/docs/icinga-for-windows/latest/doc/knowledgebase/IWKB000009/) on how to test if users are affected and how to resolve the issue once an update on the Framework is done.
