### ISSUE TITLE
Start-IcingaAgentInstallWizard ignores director's Service User setting

### ISSUE THREAD

**Issue by R-Sommer** [Icinga/icinga-powershell-framework#30]
Start-IcingaAgentInstallWizard should install icinga Windows agent taking the setting **Service User** in the director and configure **run as**

## Expected Behavior
Icinga Windows Agent is installed with run as LocalSystem 

## Current Behavior
Icinga Windows Agent is installed with run as Network Service

**Comment by LordHepipud** [comment]
Thank you for the issue. I re-checked with my config locally and for me it is working.
Could you please specify which Director version you are having installed?

This issue was fixed on the Director with v1.6.1: https://github.com/Icinga/icingaweb2-module-director/issues/1297

**Comment by LordHepipud** [comment]
Nervermind - found the issue. I already fixed it locally but forgot to push the commit.
