### ISSUE TITLE
[Feature-Request] Hide password (parameter) in error output

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icinga-powershell-framework#301]
I created some checks with the iciga-powershell-framework. With this I have to connect to an API to catch data and proccess them. So I have to pass username/password. In Icingaweb and director it is possible to hide the credentials. 

You wrote the function "Exit-IcingaExecutePlugin" in that way, that, if there is an error,  the complete function call is also in the output:

```
catch {
        $ExMsg      = $_.Exception.Message;
        $StackTrace = $_.ScriptStackTrace;

        Write-IcingaConsolePlain '[UNKNOWN] Icinga Exception: {0}{1}{1}CheckCommand: {2}{1}Arguments: {3}{1}{1}StackTrace:{1}{4}' -Objects $ExMsg, (New-IcingaNewLine), $Command, $args, $StackTrace;
        exit 3;
    }

```
For security reasons such credentials parameters should be hidden. I think about a function like the Icingaweb-module "monitoring" in the scurity tab. 
I know that PowerShell offers - in contrast to the checks on Linux - a SecureString function/type, but I prefer to complete hide them in the output :-) 
It looks like that icingaweb doesn't hide them from the output only in the custom vars. If you think it's better to create an feature request there, I will do ;-)

**Comment by LordHepipud** [comment]
Thank you for the report. Do you have an example output for me, which displays the issue?

I just tried with the CPU plugin and some weird exceptions, including a `SecureString` as password:

```powershell
icinga { Exit-IcingaExecutePlugin -Command Invoke-IcingaCheckCPU -Password (ConvertTo-IcingaSecureString 'test') }

[UNKNOWN] Icinga Exception: Die Benennung "df" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.

CheckCommand: Invoke-IcingaCheckCPU
Arguments: -Password System.Security.SecureString

StackTrace:
bei Invoke-IcingaCheckCPU, C:\Development\Testing Environments\WindowsPowerShell\Modules\icinga-powershell-plugins\plugins\Invoke-IcingaCheckCPU.psm1: Zeile 60
bei Exit-IcingaExecutePlugin, C:\Development\Testing Environments\WindowsPowerShell\Modules\icinga-powershell-framework\1.6.0\lib\icinga\plugin\Exit-IcingaExecutePlugin.psm1: Zeile 17
bei <ScriptBlock>, <Keine Datei>: Zeile 1
bei <ScriptBlock>, <Keine Datei>: Zeile 24
```

This would be the handling as well on how Icinga is rendering the check execution. Passwords or general "secure" content should always be assigned to `SecureString`. If a plugin contains a `SecureString` as argument, the customvar will be flagged as `hidden` inside the Director and internally being render with something like this

```powershell
(ConvertTo-IcingaSecureString 'your_password')
```

The only way the password should be visible, is as follows:

* Access to the Icinga Director Config preview
* Access to the Icinga Director check inspect view
* Using plain string for a secure string argument, which returns this:

```powershell
[UNKNOWN] Icinga Exception: Die Argumenttransformation für den Parameter "Password" kann nicht verarbeitet werden. Der Wert "test" vom Typ "System.String" kann nicht in den Typ "System.Security.SecureString" konvertiert werden.

CheckCommand: Invoke-IcingaCheckCPU
Arguments: -Password test

StackTrace:
bei Exit-IcingaExecutePlugin, C:\Development\Testing Environments\WindowsPowerShell\Modules\icinga-powershell-framework\1.6.0\lib\icinga\plugin\Exit-IcingaExecutePlugin.psm1: Zeile 17
bei <ScriptBlock>, <Keine Datei>: Zeile 1
bei <ScriptBlock>, <Keine Datei>: Zeile 24
```

I can work on something that this message will no longer appear and the input is not shown. For the rest I'm not sure if there is a problem at all.

Opinions?

**Comment by LordHepipud** [comment]
Play around a little with the handling.

Error handling in case you use `String` for a `SecureString` argument:

```powershell
icinga { Exit-IcingaExecutePlugin -Command Invoke-IcingaCheckCPU -Password 'test' };

[UNKNOWN] Icinga Exception: Cannot bind parameter Password. Cannot convert the provided value for argument "Password" of type "System.String" to type "System.Security.SecureString".

CheckCommand: Invoke-IcingaCheckCPU
Arguments: Hidden for security reasons

StackTrace:
bei Exit-IcingaExecutePlugin, C:\Development\Testing Environments\WindowsPowerShell\Modules\icinga-powershell-framework\1.6.0\lib\icinga\plugin\Exit-IcingaExecutePlugin.psm1: Zeile 17
bei <ScriptBlock>, <Keine Datei>: Zeile 1
bei <ScriptBlock>, <Keine Datei>: Zeile 24
```

and the regular exception if anythig else goes wrong:

```powershell
[UNKNOWN] Icinga Exception: Die Benennung "df" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.

CheckCommand: Invoke-IcingaCheckCPU
Arguments: -Password System.Security.SecureString

StackTrace:
bei Invoke-IcingaCheckCPU, C:\Development\Testing Environments\WindowsPowerShell\Modules\icinga-powershell-plugins\plugins\Invoke-IcingaCheckCPU.psm1: Zeile 60
bei Exit-IcingaExecutePlugin, C:\Development\Testing Environments\WindowsPowerShell\Modules\icinga-powershell-framework\1.6.0\lib\icinga\plugin\Exit-IcingaExecutePlugin.psm1: Zeile 17
bei <ScriptBlock>, <Keine Datei>: Zeile 1
bei <ScriptBlock>, <Keine Datei>: Zeile 24
```

**Comment by LordHepipud** [comment]
Can you please test the linked PR if this resolves the issue or helps to you secure the content better?
I think this is the best option, allowing debugging purpose and not spoiling any passwords or secure information.

**Comment by stevie-sy** [comment]
Here is a requested output of my check which happens during development:
![image](https://user-images.githubusercontent.com/38723488/126163717-d5059743-ee1e-4b67-928c-2983e4978917.png)

Ok, I'll see you're idea. You hide every param with the Type SecureString. If this is the way to go, then it's something for the developer guide to like this. 
Another idea from my side, would be that every parameter which contains "password" will be hidden from the  exception output.  But this would also be something for the development guide. 

Anyway: I'll test this the next few days incl. director.

**Comment by LordHepipud** [comment]
Thank you for the input. In general you should always use `SecureString` for sensitive information. I will update the developer guide for this, as this should be best practice.

An IDE like VS Code will also tell you, that once you use a variable with the name `Password` , to consider using `SecureString` instead of plain `String`.

As the list of variables to contain such things like `pass`, `password`, `secret` and so on is way too long for filtering, I think the best option is to just stick with `SecureString` in general.

**Comment by stevie-sy** [comment]
While developting my check, I used the/our Linux checks as a guide so that we had a line. Now I have change password-param to SecureString. And I like it. 👍  

The Output is like expected: 
![image](https://user-images.githubusercontent.com/38723488/126649029-ea977b0f-d72e-4688-88a3-ca8f4d6b41e8.png)

To set the password with `(ConvertTo-IcingaSecureString 'your_password')` in the service definition in the director works also fine.

Now I wish the bash has also a function like this 😄 

So great job!

**Comment by LordHepipud** [comment]
Thank you very much - looks great. Does the PR work if you use a plain string for the secure string argument? The entire argument string should then be hidden, for security reasons.

Once this works as well, I will merge the PR and it will apply with 1.6.0

**Comment by stevie-sy** [comment]
Sadly, if I write a plain password instead of the convert function, it doesn't work. Unfortunately, the Powershell interpreter strikes here. Because the argument can't be transformed. The result is the plain password again in the error message. 

![image](https://user-images.githubusercontent.com/38723488/126743277-bf77e5b6-4bfb-4b65-8357-1b864e6adbba.png)

**Comment by LordHepipud** [comment]
Yes, this is the old behavior. But this should be fixed with the linked PR.

It should look like this:

```powershell
icinga { Exit-IcingaExecutePlugin -Command Invoke-IcingaCheckCPU -Password 'test' };

[UNKNOWN] Icinga Exception: Cannot bind parameter Password. Cannot convert the provided value for argument "Password" of type "System.String" to type "System.Security.SecureString".

CheckCommand: Invoke-IcingaCheckCPU
Arguments: Hidden for security reasons

StackTrace:
bei Exit-IcingaExecutePlugin, C:\Development\Testing Environments\WindowsPowerShell\Modules\icinga-powershell-framework\1.6.0\lib\icinga\plugin\Exit-IcingaExecutePlugin.psm1: Zeile 17
bei <ScriptBlock>, <Keine Datei>: Zeile 1
bei <ScriptBlock>, <Keine Datei>: Zeile 24
```

**Comment by stevie-sy** [comment]
Omg, I downloaded the wrong repo for testing ...

Everything fine, so perfect! 🥇 
![image](https://user-images.githubusercontent.com/38723488/126765708-dd7c3f4c-a952-4600-927f-599be582fc8a.png)
