### ISSUE TITLE
Start-IcingaAgentInstallWizard creates director host object without ip address

### ISSUE THREAD

**Issue by R-Sommer** [Icinga/icinga-powershell-framework#31]
## Expected Behavior
Start-IcingaAgentInstallWizard should create a director host object with its ip address or its fqdn

## Current Behavior
Host address is empty

**Comment by log1-c** [comment]
Can confirm this:
![image](https://user-images.githubusercontent.com/24474580/69873934-07111b00-12ba-11ea-9983-0029f612dd55.png)

Wizard Output:
```
The wizard is complete. These are the configured settings:
========
-UseDirectorSelfService 1
-DirectorUrl http://192.168.63.35/icingaweb2/director
-AddFirewallRule True
-AcceptConnections True
-Ticket '53...      <<< 
-EmptyTicket
-InstallFrameworkPlugins 1
-PluginsUrl 'https://github.com/Icinga/icinga-powershell-plugins/archive/v1.0.0-rc1/v1.0.0-rc1.zip'
-InstallFrameworkService 1
-FrameworkServiceUrl 'https://github.com/Icinga/icinga-powershell-service/releases/download/v1.0.0/icinga-service-v1.0.0
.zip'
-ServiceDirectory 'C:\Program Files\icinga-framework-service\'
-ServiceBin 'C:\Program Files\icinga-framework-service\icinga-service.exe'
-RunInstaller
```

I think there is also a ' missing in the Wizards output, maybe that correlates with the problem?

**Comment by LordHepipud** [comment]
This is actually not supported yet, because we are discussing internally on how to approach this in the future.

Do you have other ways in your environment available to set / override the IP (like Director imports) or are you using the module only?

This will help in providing a proper solution in the future.

**Comment by R-Sommer** [comment]
If the question belongs to me: I just use the module.

**Comment by LordHepipud** [comment]
Basicly the first draft would look like the following:

* The Framework will ask during the Wizard which Address the Host should be registered with
* You can either use the auto-detected address then, use a manual entered one or leave it alone
* The Director will in the future no longer override empty values. Which means if an address is set on the Director and you register the Host without IP, it will be left alone

Any suggesstions / extensions / ideas / improvements on this required?

**Comment by R-Sommer** [comment]
- If there is just one NIC the Framework should not ask
- If a client has multiple NICs the NIC within the Master's ip network should be selected
- An option should allow to register with FQDN instead (which is required if DHCP is used)
- The Wizard should ask about the parent zone
