### ISSUE TITLE
After uninstall other programs with own PowerShell-Modul (e.g. MS SCOM), Icinga-PowerShell-Framework doesn't work

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icinga-powershell-framework#313]
Because of using more and more Icinga Agent on our Windows servers incl. more and more checks from the icinga-PowerShell-Framework, my colleagues from the server admin uninstall SCOM where it isn't needed anymore. 

Here we observe that after uninstalling it on Windows 2012R2 servers, every check quits with following output:

![image](https://user-images.githubusercontent.com/38723488/128063100-ee9ce809-efbf-43dc-8edc-59a4f5425ac8.png)

On our servers with Windows 2016 and 2019 everyhting is fine. 

background information:
SCOM install also a PowerShell module. But not in the standard directory C:\Program Files\WindowsPowerShell\Modules. It installs it under C:\Program Files\Microsoft Monitoring Agent\PowerShell\Microsoft.MonitoringAgent.PowerShell
![image](https://user-images.githubusercontent.com/38723488/128063507-9a285b6c-66c5-4d0c-8757-24892e3acd67.png)

We don't know what happens during (un)installation because SCOM is closed source. But something is happening with PowerShell and as result this strange behavior. There are also no eventlogs. 

The only thing which helps is to restart the icinga daemon. 

We want to mentioned it but we think also this isn't something what could be really fixed. So maybe it's something for your knowledge base.

**Comment by LordHepipud** [comment]
Thank you for the report!

If you restart the Icinga Agent, everything works again as expected?

**Comment by stevie-sy** [comment]
yes

**Comment by stevie-sy** [comment]
Do you need further information to put this into the KB in your docs?

**Comment by tbauriedel** [comment]
ref/NC/761567
