### ISSUE TITLE
Invoke-IcingaCheck... missing Cmdlets 

### ISSUE THREAD

**Issue by puseidr** [Icinga/icinga-powershell-framework#36]
I've installed the framework (1.0.0-rc2) via the kickstart-script on fresh VMs (Win 10, Windows Server 2016/2019)

When running a Invoke-IcingaCheckXXX cmdlet i get an error 
## Expected Behavior
<pre>Use-Icinga;
Invoke-IcingaCheckCpu -Warning 50 -Critical 75</pre>
i should see some output about the perfdata like:
<pre>
[OK]: Check package "CPU Load" is [OK]| 'Core #0'=4,59%;50;75;0;100 'Core #1'=0,94%;50;75;0;100 'Core #2'=11,53%;50;75;0;100 'Core #3'=4,07%;50;75;0;100</pre>

## Current Behavior
<pre>Invoke-IcingaCheckCpu : Die Benennung "Invoke-IcingaCheckCpu" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der
Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ Invoke-IcingaCheckCpu -Warning 50 -Critical 75
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-IcingaCheckCpu:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException</pre>

## Steps to Reproduce (for bugs)
install the framework with kickstart-script 

<pre>Do you provide an own repository for the Icinga PowerShell Framework? (y/N):
Which version to you want to install? (snapshot/STABLE):
The following directories are available for modules:
[0]: C:\Users\Administrator\Documents\WindowsPowerShell\Modules
[1]: C:\Program Files\WindowsPowerShell\Modules (Recommended)
[2]: C:\Windows\system32\WindowsPowerShell\v1.0\Modules
Where do you want to install the module into? ([0-2]): 1
Downloading Icinga Framework into "C:\Users\ADMINI~1\AppData\Local\Temp\19\icinga-powershell-framework-zip"
Installing module into "C:\Program Files\WindowsPowerShell\Modules"
Installing new module version
Unblocking Icinga Framework Files
Framework seems to be successfully installed
To use this framework in the future, please initialize it by running the command "Use-Icinga" inside your PowerShell
Do you want to run the Icinga Agent Install Wizard now? You can do this later by running the command "Start-IcingaAgentInstallWizard" (Y/n): n
PS C:\Windows\system32> Use-Icinga;
PS C:\Windows\system32> Install-IcingaFrameworkPlugins;
Do you provide a custom repository for "Icinga Plugins"? (y/N):
Which version to you want to install? (snapshot/stable) (Default: "stable"):
Downloading "Icinga Plugins" into "C:\Users\Administrator\AppData\Local\Temp\19\tmp_icinga1766152149.d"
Installing module into "C:\Users\Administrator\AppData\Local\Temp\19\tmp_icinga1766152149.d"
Using content of folder "C:\Users\Administrator\AppData\Local\Temp\19\tmp_icinga1766152149.d\icinga-powershell-plugins.zip" for updates
Plugin Module Directory "C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins" is not present. Creating Directory
Copying files to plugins
Cleaning temporary content
Unblocking Icinga PowerShell Files
Icinga Plugin update has been completed

Name                           Value
----                           -----
PluginUrl                      https://github.com/Icinga/icinga-powershell-framework/archive/v1.0.0-rc2/v1.0.0-rc2.zip
</pre>

## Context
I've sucessfully installed the framework (1.0.0rc1) on some VMs some weeks ago, but now even rc1 (installed on fresh VMs) does not serve the cmdlets.

## Your Environment
* PowerShell Version used (`$PSVersionTable.PSVersion`):
<pre>Major  Minor  Build  Revision
5      1      17763  771
</pre>

* Operating System and version (`Get-WmiObject Win32_OperatingSystem | Select-Object Version, BuildNumber, Caption`):
<pre>Version    BuildNumber Caption
10.0.17763 17763       Microsoft Windows Server 2019 Standard</pre>

even tested with a buch of other vms (Windows 10, Windows Server 2016)

**Comment by LordHepipud** [comment]
Are the plugins properly installed?

```powershell
Get-Module -ListAvailable 'icinga-powershell-plugins';
```

**Comment by puseidr** [comment]
no there is no output of this command. 
only on the old VMs (framework rc1 installed) i see the installed module
<pre>


    Verzeichnis: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.0      icinga-powershell-plugins           {Use-IcingaPlugins, Import-IcingaPlugins, Publish-IcingaPl...
</pre>

**Comment by LordHepipud** [comment]
This is weird. Is there anything present within the plugin folder:

```powershell
Get-ChildItem 'C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\';
```

What happens if you use

```powershell
Use-IcingaPlugins;
```

And run a command afterwards? Does this work?

**Comment by puseidr** [comment]
the folder "C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\" is empty and the command "Use-IcingaPlugins" is not awailable
<pre>Use-IcingaPlugins : Die Benennung "Use-IcingaPlugins" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad
korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ Use-IcingaPlugins;
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Use-IcingaPlugins:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
</pre>

**Comment by puseidr** [comment]
when i look inside the C:\Users\Administrator\AppData\Local\Temp\xzy\ folder i see a file called "icinga-powershell-plugins.zip" but inside is the folder "icinga-powershell-framework-1.0.0-rc2". 

It looks Like the cmdlet **Install-IcingaFrameworkPlugins** is downloading the wrong file.

**Comment by LordHepipud** [comment]
I have just tested this on a fresh installed system. This error occures indent - in case the stable release of the Plugins is installed.
Snapshots are working fine. And yes - the stable release is download the Framework instead of the Plugins because of the wrong Url -_-

**Comment by LordHepipud** [comment]
I just released RC3 - this will fix this issue. Sorry for the trouble !
