### ISSUE TITLE
Error: The remote host for address "<remote address>" could not be resolved while trying to regsiter new host

### ISSUE THREAD

**Issue by KineticFox** [Icinga/icinga-powershell-framework#372]
## Expected Behavior
The Host got created in the director already. Now i just want to install the Windows Agent on this Host and connect via self service api to the director and "merge" the existing Host with this machine.
If the host wasnt created before the agent installation and the creating host process works just fine, but in my case i have to create a host and afterwards install the agent and connect to the director.
Is there a way the director can detect that the host that should be created already exists and skip this step and only connects the agent to the alredy existing host?

## Current Behavior
if i try to run the Agentinstall wizard ps Script again i get this error: Error: The remote host for address "<remote address>" could not be resolved

## Steps to Reproduce (for bugs)
1. create Host manually via Icinga director web gui
2. afterwards execute `Start-IcingaAgentInstallWizard -SelfServiceAPIKey $apitoken -EmptyCA 0 -UseDirectorSelfService 1 -DirectorUrl $url -OverrideDirectorVars 0 -ConvertEndpointIPConfig 1 -Ticket ''	-EmptyTicket 1 -InstallFrameworkPlugins 0 -InstallFrameworkService 0 -CAEndpoint $ca -debug -RunInstaller; `  local on the created Host

## Your Environment
* PowerShell Version used: 5.1

* Operating System and version: 6.3.9600 9600,  Microsoft Windows Server 2012 R2 Datacenter

**Comment by LordHepipud** [comment]
Hello and thank you for the issue. Yes, this works just fine as long as the Windows machine can properly connect to the Icinga Director.

It is important, that the host is set as `Icinga2 Agent` including the template of the host you want to assign. In addition, the `Agent` tab of the Icinga Director should tell you on how to register the host with the proper key. In case there is already a button wtih "Drop Host Key", you can't re-create the host unless the Self-Service key is present on the local Windows machine.

The Icinga Director Self-Service API will claim the host, as long as no key to the host is already assigned. Your use-case should therefor work.

With Icinga for Windows v1.6.1 we will add an improved error handling for this, telling users what exactly might be wrong while using the API. The release for v1.6.1 is scheduled for tomorrow.

**Comment by KineticFox** [comment]
Ok thanks for the fast reply. 
So as long as on the local host no api key exists both hosts get "merged"?!

**Comment by KineticFox** [comment]
>In case there is already a button wtih "Drop Host Key", you can't re-create the host unless the Self-Service key is present on the local Windows machine.

Now i got it working. The problem was i tested with the same host and never recreated a clean host...
Now the agent wizard is overwritng the clean existing host in the director ;)

Thank you for your help!
(And yes more specific error messages can help a lot :D)

**Comment by LordHepipud** [comment]
You are welcome. As long as the API key is not set on the host on the Icinga Director it will work.

In case a host key is set on the Icinga Director, a registration is not possible, because the host is already claimed and the key needs to be dropped.

If a host key is set and it matches the stored key on the Windows machine, it will work just fine.

Icinga for Windows will check dynamically the key you provide by using the wizard and arguments and a possible stored key. In case both keys fail, you will receive an error.

If your template key fails but your host key is fine, then Icinga for Windows will simply continue.
