### ISSUE TITLE
Icinga Powershell Service contains a possible memory leak

### ISSUE THREAD

**Issue by Byolock** [Icinga/icinga-powershell-framework#379]
## Expected Behavior
Running a background Daemon should not increase its memory footprint over time.

## Current Behavior
In about 11 days the memory usage reached about 4GB on several machines.

## Steps to Reproduce (for bugs)

1. Install Icinga2 & Powershell Framework with following script :
```
[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -Confirm:$False
If(-not(Get-InstalledModule icinga-powershell-framework -ErrorAction silentlycontinue)){
    Install-Module icinga-powershell-framework -Confirm:$False -Force
}
Use-Icinga;
Start-IcingaAgentInstallWizard `
    -DirectorUrl            'https://xxxxxxxxxxxxxxxxxxxx/icingaweb2/director/' `
    -SelfServiceAPIKey      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' `
    -UseDirectorSelfService 1 `
    -OverrideDirectorVars   0 `
    -InstallFrameworkPlugins 1 -PluginsUrl 'https://github.com/Icinga/icinga-powershell-plugins/archive/refs/tags/v1.5.1.zip' `
    -InstallFrameworkService 1 -FrameworkServiceUrl 'https://github.com/Icinga/icinga-powershell-service/releases/download/v1.1.0/icinga-service-v1.1.0.zip' -ServiceDirectory 'C:\Program Files\icinga-framework-service\' `
    -EmptyCA 1 `
    -Reconfigure `
    -RunInstaller
Register-IcingaServiceCheck -CheckCommand 'Invoke-IcingaCheckCPU' -Interval 30 -TimeIndexes 1, 3, 5, 15;
Restart-IcingaService 'icingapowershell';
```
2.  Create a Service Check with the 'Invoke-IcingaCheckCPU' command to execute every 60s
3.  Create a Service Check with the 'Invoke-IcingaCheckDiskHealth' command to execute every 300s
4.  Create additional Service Checks with the 'network-windows, disk-windows, memory-windows' commands to execute every 300s
5. wait a few days

## Your Environment

* PowerShell Version used (`$PSVersionTable.PSVersion`): 5.1.19041.1237

* Operating System and version (`Get-IcingaWindowsInformation Win32_OperatingSystem | Select-Object Version, BuildNumber, Caption`): 
```
Version    BuildNumber Caption
-------    ----------- -------
10.0.19042 19042       Microsoft Windows 10 Pro
```

* Registered Background Daemons
```
Name                           Value
----                           -----
Start-IcingaServiceCheckDaemon {}
```

* Registered Service Checks
```
[Notice]: Service Id: 5275219864641021224811420224776891459631192206
[Notice]:
Name                           Value
----                           -----
CheckCommand                   Invoke-IcingaCheckCPU
Interval                       30
Arguments
Id                             5275219864641021224811420224776891459631192206
TimeIndexes                    {1, 3, 5, 15}
```

EDIT: I noticed I'm running an old version of the plugins. I did an update to 1.6.0 now.

**Comment by Byolock** [comment]
I just noticed that this does not seem to happen on our Server 2012 R2 with Powershell Version 5.1.14409.1005.
On Server 2008R2 (same Powershell Version) the Issue is present.

**Comment by Byolock** [comment]
It's present on every OS we use (2008R2, 2012R2, Windows 8, Windows 10). I initially thought it does **not** happen on 2012R2 but it just took longer to appear on these systems for some reason. 
The `Your Environment` part in my initial post has the environment of a windows 10 machine which also has this issue.

**Comment by LordHepipud** [comment]
Thank you very much. I'm already trying to investigate which of the checks is causing the memory leak, but at the moment my test environments are consistent with the memory usage. I will try dig deeper into this.

Are you having every single check configured in the background?

Could you please share the entire registered checks including possible set arguments?

**Comment by bibbs** [comment]
While seeing that a possible fix is already on its way ^^ I can confirm the initial reported problem.
I am using am minimal (testing) setup of background checks:

`Register-IcingaBackgroundDaemon -Command 'Start-IcingaServiceCheckDaemon';`
`Register-IcingaServiceCheck -CheckCommand 'Invoke-IcingaCheckCPU' -Interval 30 -TimeIndexes 1, 5, 15;`

While this works as intended, I am hereby getting a background "powershell.exe" process which continiously ramps up in RAM and CPU usage:
`After start : avg    5% CPU,  270 MB RAM`
`After 1 day : avg 12% CPU,  600 MB RAM`
`After 5 days: avg 20% CPU, 2900 MB RAM`

using Framework Version 1.6.1 on Windows Server 2016 (4 Cores)

**Comment by LordHepipud** [comment]
Would it be possible for you to test the linked PR and check if this resolves the problem?
Not only the PowerShell process memory consumption over time, but also system memory.

So far I'm happy with the result, but I would rather have more different environments tested in this matter.

**Comment by LordHepipud** [comment]
I did some testing now and as far as I can tell, the linked PR resolves the memory leak issue. Anyone else had the chance to test it yet?

**Comment by LordHepipud** [comment]
After lots of additional testing I came to the conclusion that the current implementation of the background daemon and service check handling is simply trash.

I will re-write the entire part to be less waste of resources, better extendable and healthier for the performance itself.

**Comment by bibbs** [comment]
I've compared now the different versions concerning the RAM and CPU consumption of the powershell.exe process in question:

before https://github.com/Icinga/icinga-powershell-framework/pull/405 ("aggressive GCing")
CPU: avg. 11% (on 4 core machine)
RAM: rising up to 5 GB

after https://github.com/Icinga/icinga-powershell-framework/pull/405 ("aggressive GCing")
CPU: avg. 16% (on 4 core machine)
RAM: 800 MB, slowly rising

after https://github.com/Icinga/icinga-powershell-framework/pull/414 ("full rewrite of daemon")
CPU: avg. <1% (on 4 core machine)
RAM: 115 MB, quite stable

The latter seems a very good fit!
(ATM there are still conflicts preventing the merge of this PR 414 to master)

**Comment by LordHepipud** [comment]
Thank you very much for testing and the comparison. That falls in-line with my internal tests at the moment.
I did a rebase of the branch as of yesterday which resolved all the conflicts and is now up-to-date with the master, including many other improvements for logging and other features.

If nothing goes horrifically wrong, I will merge the branch into the master next week.

Thank you again for the feedback!
