### ISSUE TITLE
[Feature request] Icinga2 Agent Windows Service - Recovery

### ISSUE THREAD

**Issue by bitboy85** [Icinga/icinga-powershell-framework#40]
After installation of the icinga2 agent, the windows service has no recovery options configured.
Please add "Restart Service" for first and second error by default.
merry christmas!

![icinga2service](https://user-images.githubusercontent.com/6197580/71408704-6fe07e80-263f-11ea-9b13-4d8fdedf9f77.png)

**Comment by LordHepipud** [comment]
We discussed this internally and we will integrate a function into this PowerShell Framework for Windows.
With this we keep the current state of the MSI package and the service handling but extend the possibilities for users to modify this part automated or manually.
