### ISSUE TITLE
IcingaBackgroundDaemon, does the address option work?

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icinga-powershell-framework#402]
Hello,

My environment of icinga monitoring is running on a linux platform. 
I thought to only run the framework on the windows servers/pc and then request info (curl) via the RESTApi plugins.
On 127.0.0.1 (localhost) everything works but when I try to connect from outside it doesn't work.

# Register-IcingaBackgroundDaemon -Command 'Start-IcingaWindowsRESTApi' -Arguments @{ '-Address' = '0.0.0.0'; '-Port' = 5669;......

I thought to specify 0.0.0.0 or local IP in the Daemon that the restapi could also be reached from outside. 

And when I go to check with netstat I see that the service is still running under 127.0.0.1
TCP    127.0.0.1:5669         WIN10INSIDER:0         LISTENING   [powershell.exe]

Firewall is completely off !

Is it possible that the Address option doesn't work when creating the BackGroundDaemon so that I can also address the restapi from other hosts ?
Or are there other options/services I need to configure ?

# Environment
PowerShell:
Version          : 5.1.19041.1023

Get-Module:
Script     1.7.1      icinga-powershell-framework
Script     1.7.0      icinga-powershell-plugins

regard,
Geert

**Comment by gbin2265** [comment]
I did also a little debugging of the files and I see:

New-IcingaForWindowsRESTApi
    param (
        $IcingaDaemonData,
        $Port,

$Address,
Address Missing in param bgefore Port ????			



Start-IIcingaWindowsRESTApi

    New-IcingaThreadInstance `
        -Name 'Icinga_for_Windows_REST_Api' `
        -ThreadPool $global:IcingaDaemonData.IcingaThreadPool.IcingaRESTApi `
        -Command 'New-IcingaForWindowsRESTApi' `
        -CmdParameters @{
            'IcingaDaemonData' = $global:IcingaDaemonData;
             'Port'             = $Port;            

'Address'          = $Address;
Address Missing in ComdParameters before Port ????			


Could it be that these 2 Address lines need to be added to run the service at a certain address !??

regard,
Geert

**Comment by LordHepipud** [comment]
Hello

Thank you for the issue. Yes, you are right - the Address is not handed over to the background daemon, which results in the address not being used. The address argument should be present there.

**Comment by gbin2265** [comment]
Thank you for the update!

Now I'm going to write the necessary bash scripts so that we can monitor windows servers from icinga linux platform via your framework/api.

regards,
Geert
