### ISSUE TITLE
Sync-IcingaRepository returns ConvertFrom-Json : Invalid JSON primitive

### ISSUE THREAD

**Issue by ThatRandomDude** [Icinga/icinga-powershell-framework#409]
Environment:

Windows 10 21H1 and Server 2016
Powershell 5.1 and Powershell 7.2
Icinga-Framework-Version 1.7.1

Steps to reproduce:

1. Install latest version (1.7.1) from PSGallery
2. Follow local disk example from https://icinga.com/docs/icinga-for-windows/snapshot/doc/repositorymanager/02-Sync-Repositories/
2. Error occours nearly instantly

Workaround:
Use the full path as the source:

```
 Sync-IcingaRepository`
     -Name 'Icinga Stable Local'`
     -Path 'C:\temp\icinga'`
     -Source 'http://packages.icinga.com/IcingaForWindows/stable/ifw.repo.json';
```

Possible reason:

I think the problem is here:
https://github.com/Icinga/icinga-powershell-framework/blob/3e55dbd8a5e171c088f5f66439b86c9da0139b99/lib/core/repository/Sync-IcingaRepository.psm1#L99-L103
This does not throw because it receives the directory listing.

Possible solution:

- Add a check if $RepoFileis a valid json and throw if it isn't
- Change the documentation to reference the complete path - including the json file like: 'http://packages.icinga.com/IcingaForWindows/stable/ifw.repo.json'

**Comment by LordHepipud** [comment]
Thank you for the issue. Yes, this is a bug thank you for the report. We changed the handling the web request is handled to ensure proxies are working as expected.

The problem now is, that the exception is no longer thrown there, because catched inside our function. We will fix this!
