### ISSUE TITLE
obsolete Write-IcingaConsoleNotice in Framework 1.7.1

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icinga-powershell-framework#421]
https://github.com/Icinga/icinga-powershell-framework/blob/e37f55264e620b5eb0038db3a9e4ad2acf758358/lib/core/framework/Enable-IcingaFrameworkApiChecks.psm1#L20

since the Framework includes these 2 components the Write-IcingaConsoleNotice should be removed.

Best regards Nicolas

**Comment by LordHepipud** [comment]
Yep, thats true - thanks for the report. There are more parts we need to adjust this and are aware of it.
Everything will be adjusted with 1.8.0 to also clarify configurations.
