### ISSUE TITLE
JEA not working with IcingaCheckPartitionSpace 

### ISSUE THREAD

**Issue by CHOOH1992** [Icinga/icinga-powershell-framework#437]
Hi,
I noticed that Invoke-IcingaCheckPartitionSpace was not providing results to Icingaweb:
`Check command 'Invoke-IcingaCheckPartitionSpace' does not exist.
`
Manually running this check is working fine. After some time I noticed that the host is using JEA; actually my only Server 2016 with PS 5.1 and JEA.

I tried to update the JEA-Profile, which runs into an error:
```
PS C:\Windows\system32> Update-IcingaJEAProfile
[Notice]: Writing Icinga for Windows environment information as JEA profile
[Warning]: The module "icinga-powershell-plugins" is using "Add-Type" definitions for file "C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\provider\disks\Get-IcingaDiskAttributes.psm1". Ensure you validate the code before trusting this publisher.
[Error]: Unable to include module "icinga-powershell-plugins" into JEA profile. The file "C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\provider\disks\Get-IcingaPartitionSpace.psm1" is using one or more [ScriptBlock] variables which are forbidden in JEA context.
[Notice]: Registering Icinga for Windows JEA profile
```
After uninstalling the JEA Profile and restarting Icinga (Restart-IcingaWindowsService) the console told me that the Icingaservice is no longer installed. Reinstallating the servie and rebooting the system worked fine; the server is now running without JEA.
Best regards

**Comment by LordHepipud** [comment]
This is fixed with v1.8.0 for Icinga for Windows, Plugins and v1.1.0 for Hyper-V plugins.
