### ISSUE TITLE
Get-IcingaServices returns Unknown value if using wildcard

### ISSUE THREAD

**Issue by bargru** [Icinga/icinga-powershell-framework#443]
## Expected Behavior

If using the command Get-IcingaServices with wildcards, I expect to get a list of the services where the StartType (StartMode in WMI Class) is not Unknown.

Example command: `$FetchedServices = Get-IcingaServices -Service User*`

## Current Behavior

The command is finding some services:
```
PS C:\Windows\system32>$FetchedServices
Name                           Value
----                           -----
UserDataSvc_1421abd            {metadata, configuration}
UserManager                    {metadata, configuration}
UserDataSvc_13e5af             {metadata, configuration}
```

But all the StartType fields have a Unknown state:
```
PS C:\Windows\system32> $FetchedServices.Values.configuration.StartType

Name                           Value
----                           -----
value                          Unknown
raw                            5
value                          Unknown
raw                            5
value                          Unknown
raw                            5
```
The commands were executed in an elevated ps session.

If I execute `$FetchedServices = Get-IcingaServices` none of the services has the state Unknown. Also if I filter for a specific service a valid StartupType is shown.

```
PS C:\Windows\system32> $FetchedServices = Get-IcingaServices -Service UserManager
PS C:\Windows\system32> $FetchedServices.Values.configuration.StartType

Name                           Value
----                           -----
value                          Automatic
raw                            2
```

## Possible Solution

I have no idea if this is a WMI bug, a bug in the Get-IcingaServices command or the Get-IcingaWindowsInformation command.

## Steps to Reproduce (for bugs)

Just use the commands from above. The services should be present on every Windows System starting with Windows 10 or Windows Server 2016.

## Context

Problem was found when trying to use the command  `Invoke-IcingaCheckService -Service 'User*' -FilterStartupType 'Automatic'` from the icinga-powershell-plugins.

## Your Environment

* PowerShell Version used (`$PSVersionTable.PSVersion`): 
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  2268
```

* Operating System and version (`Get-IcingaWindowsInformation Win32_OperatingSystem | Select-Object Version, BuildNumber, Caption`):
 ```
* Version    BuildNumber Caption
-------    ----------- -------
10.0.17763 17763       Microsoft Windows Server 2019 Datacenter
```

* icinga-powershell-framework: `1.7.1`

**Comment by LordHepipud** [comment]
Hello

Thank you for the issue. Could you please test the linked PR? This should resolve the problem.

Thanks alot!

**Comment by bargru** [comment]
I tested the changed code. Works perfectly!

Thank you for the quick fix!
