### ISSUE TITLE
Unable to connect to the remote server [EventID: 1553] 

### ISSUE THREAD

**Issue by pakyg** [Icinga/icinga-powershell-framework#483]
Hi, I'm having trouble with invoke PS plugins working with the API.
I state that I have updated all the modules to the latest version, following all the various steps recommended for installation.
I get the error "Unable to connect to the remote server" EventID 1553. I have registered the various PS plugins, with the command: Add-IcingaRESTApiCommand -Command 'Invoke-IcingaCheck *' -Endpoint 'apichecks' -Whitelist ;.
Can you help me solve the problem?
Thanks so much,
Greetings

![Error_eventid](https://user-images.githubusercontent.com/70367256/125810514-00316c78-806d-40bd-a65f-064a34c9a7cd.png)

![Error_EventID_1553](https://user-images.githubusercontent.com/70367256/125810549-0710c274-31a7-4f61-8ec8-a4850048916a.png)

**Comment by pakyg** [comment]
I closed the powershell session and restarted the service, but the problem persists..
![image](https://user-images.githubusercontent.com/70367256/154446499-47ed9ab2-348d-4bdd-8fcf-c4d9d493b8f5.png)

**Comment by LordHepipud** [comment]
Can you please test the linked PR? I created a patch that should resolve the certificate lookup on custom hostname or DNS/Domain mismatches.

Once you installed the PR, you can run this command to test if you now receive a certificate:

```powershell
icinga { return (Get-IcingaAgentHostCertificate) } -RebuildCache;
```

You should then be pointed to the certificate you have manually used so far. If this is the case, register the background daemon again:

```powershell
Register-IcingaBackgroundDaemon -Command Start-IcingaWindowsRESTApi;
```

and restart the Icinga for Windows service:

```powershell
Restart-IcingaWindowsService
```

atleast this issue is then resolved. One the service is restarted, wait a few seconds and try this again:

```powershell
netstat -aon | ForEach-Object { if ($_ -like '*5668*') { $_ } }
```

**Comment by pakyg** [comment]
It does not find the certificate again .. I do not understand why, before we had entered it manually and it worked
![image](https://user-images.githubusercontent.com/70367256/154455133-92808f72-f0ee-4384-99a6-543abf29663e.png)

**Comment by LordHepipud** [comment]
So basically what I don't understand is the problem in your environment. Granted, the SSL lookup should now work better with the PR, but still there is no result.
Which is weird.

Can you please have a look at this file:

```text
C:\ProgramData\icinga2\etc\icinga2\constants.conf
```

There should be an entry called

const NodeName = "<your hostname>"

This is the one that should match the name of the `.crt` file - is this correct?

**Comment by pakyg** [comment]
const NodeName is equal to localhost, instead it should be equal to the server name (scdbmop0170)
![image](https://user-images.githubusercontent.com/70367256/154457109-a4b81764-9e49-40ec-9b3d-e994287eff39.png)

I don't understand how this is possible.. Do I try to change it manually?

**Comment by LordHepipud** [comment]
I have no idea on why this entry is not set. Is your Icinga Agent setup working properly in general?

How is the object name inside your Icinga 2 setup configured?

You have to replace the entry

```
//const Nodename = "localhost"
```

with

```
const NodeName = "<object name of the host in icinga2>"
```

I assume this could be `scdbmop0170.domain`, as the certificate was generated with the domain at the end.
Then try to restart the Icinga Agent.

Once done, the command I mentioned before should lookup the certificate properly with the fixed PR.

**Comment by pakyg** [comment]
Yes, the Icinga agent works quietly, manages to schedule all the check in console.
I changed the NodeName by entering the correct name and restarted the Icinga agent .. But it still can't find the certificate ..
![image](https://user-images.githubusercontent.com/70367256/154458974-52324791-5003-4e4f-98ad-6680924dc176.png)

**Comment by LordHepipud** [comment]
You have to remove the two `//` for the change to apply, but still the lookup should work.
Have you installed the Framework version from the linked PR?

If you run `icinga -Shell`, does it say v1.9.0 at the top?

**Comment by pakyg** [comment]
Ok sorry, I fixed the name of the constants.conf, restarted the Icinga service and launched the required commands.
We are currently using the latest version "1.8.0", is that correct?

![image](https://user-images.githubusercontent.com/70367256/154461573-2ffb9466-7d68-4657-8e0c-26cbca6621f7.png)

**Comment by LordHepipud** [comment]
I have honestly no idea, on why this problem persist. Can you locally run this command while the service is running?

```powershell
Enable-IcingaUntrustedCertificateValidation;
Set-IcingaTLSVersion;
Invoke-WebRequest -UseBasicParsing -Uri 'https://localhost:5668/v1';
```

is there output coming back or simply returning an error?

**Comment by pakyg** [comment]
Unfortunately, I keep encountering the same problem, even when launching the "Enable-IcingaUntrustedCertificateValidation" parameter:
![image](https://user-images.githubusercontent.com/70367256/154662179-ec7ee279-1638-4c2f-a709-f3b1374d1f0e.png)

**Comment by LordHepipud** [comment]
Does the EventLog show something in addition when trying to connect to the REST api?

**Comment by LordHepipud** [comment]
If not, can you please run

```powershell
Enable-IcingaFrameworkDebugMode;
Restart-IcingaWindowsService;
```

and try to connect from the PowerShell again? Please stop the Icinga Agent service before.

Then we can trace this connection attempt within the EventLog and check, if actually the port is opened and where it dies.

**Comment by pakyg** [comment]
The event log shows nothing when I try to connect to RestApi:
![image](https://user-images.githubusercontent.com/70367256/154692830-06aa9327-2f2c-4b71-9a20-35d86aaf03f6.png)


I tried to disable the Icinga 2 service and run the recommended commands:
![image](https://user-images.githubusercontent.com/70367256/154693311-85f7597e-72dc-48e9-a00b-de4b51524e84.png)

Currently I am not seeing errors on rest-api and eventid anymore. I can't understand why, in any case trying to run the invoke, it keeps failing.

Thank you

**Comment by LordHepipud** [comment]
You have to navigate to the Application and Serices Log on the left side, there is the `Icinga for Windows` EventLog which v1.8.0 should have already written data into.

Everything can be found there.

**Comment by pakyg** [comment]
That's right, the various errors are still there
![image](https://user-images.githubusercontent.com/70367256/154919567-d8a515e4-b49a-40f1-9964-1238d23962c6.png)

Thanks

**Comment by pakyg** [comment]
Update: 
Port 5668 appears not to be listening

![image](https://user-images.githubusercontent.com/70367256/154942246-3def359e-4d61-4ef1-a8e0-8a55f2b710d6.png)

**Comment by LordHepipud** [comment]
Can you please stop the Icinga Agent and the Icinga for Windows service, clear the EventLog, Restart the Icinga for Windows service and try to connect once.

There should be a lot of debug outputs present and I would like to see, what happens there. Maybe you can upload the logfile somewhere so I can review it afterwards?
Please ensure confidental inforamtion is reoved before.

**Comment by pakyg** [comment]
After rebooting it gave me the error "2000" on the certificate.
But we had already installed the .crt with the command "Install-IcingaForWindowsCertificate -CertFile 'C: \ ProgramData \ icinga2 \ var \ lib \ icinga2 \ certs \ scdbmop0170 ..... crt'"


I did the required steps, cleaned the log and restarted the services, i am attaching the print and log of Icinga:
[scdbmop0170_eventlog_icingaforwindows.zip](https://github.com/Icinga/icinga-powershell-framework/files/8109947/scdbmop0170_eventlog_icingaforwindows.zip)

When it restarts, it appears that it loses the certificate

**Comment by LordHepipud** [comment]
Thank you - I minimized the comment, to remove access to the information.

I honestly have no idea on hw to proceed in this case. I would require remote access to the machine for troubleshooting.
From mypoint of view, we did everything that is required to get this working. As there are many different customers with working environments, this is issue not widely spread or something else is missing. I honestly do however not know, which steps are missing in this case.

**Comment by pakyg** [comment]
Hi, I have done further checks.
We managed to install the certificate correctly, now port 5668 is listening.
When I try to access "https: // localhost: 5668 / v1", it reports me the usual errors.
Having fixed the certificate (before we didn't even have the door listening), I have a doubt:
Should the registration of services with the Api daemon be registered on time? It seems as if they are not registered correctly.
The commands I give him to record them are the following:

"Register-IcingaBackgroundDaemon -Command 'Start-IcingaWindowsRESTApi';"

"Add-IcingaRESTApiCommand -Command 'Invoke-IcingaCheck *' -Endpoint 'apichecks';"

If the services are registered correctly, why can't I see what commands are registered with the api daemon? "Show-IcingaApiCmmands" reports the error.

Where am I doing wrong?

Thanks so much for the support

![image](https://user-images.githubusercontent.com/70367256/155953735-7b3b217e-a4e8-43ed-ae67-8438430d03d0.png)

**Comment by LordHepipud** [comment]
I'm not entirely sure. The folder is created once you install this specific certificate and also permissions should be created along the way.
The untrusted errors are normal, if you are not using `Enable-IcingaUntrustedCertificateValidation` for the session. Icinga for Windows will do this internally always for the call, including the setting of the TLS version, to ensure that the connection is possible.

However, you should receive SSL/TLS error while connecting if you are not using `Enable-IcingaUntrustedCertificateValidation`. But the error in this case is that something went wrong after the handshake was successfully made.

All I could think of is that the local TLS configuration is not making it possible to properly "validate" the certifiicate.

**Comment by pakyg** [comment]
Hi, just an update, we have finally got on top of the API problem.
During the installation phase, we were unable to install the various certificates correctly, we solved it by importing both certificates (ca.crt and server_fqdn.crt) into the Trusted Root store.
If we do not import the certificates the port "5668", will not go into the listening state.
________________________________________________________________________________________________________________________________
Also just a quick note to cleanly remove the icinga-powershell-service on Windows server 2012 we added "-confirm:$false" to the following command:

Uninstall-IcingaFrameworkService -Path 'C: \ Program Files \ Icinga-Framework-Service \ icinga-service.exe' -User 'LocalSystem' -confirm:$false;

On Windows server 2012, this command was waiting for user input
![image](https://user-images.githubusercontent.com/70367256/157895022-49713ab3-790e-4381-96e7-5c8146182168.png)
This was happening on framework version 1.9.0.

Thanks :)

**Comment by LordHepipud** [comment]
I created a new issue regarding the required user input: https://github.com/Icinga/icinga-powershell-framework/issues/492

The REST-Api error will be easier detectable, as we now added a check for the signing status: https://github.com/Icinga/icinga-powershell-framework/pull/495
