### ISSUE TITLE
Icinga2 Agent shows password in cmd on failure

### ISSUE THREAD

**Issue by Mordecaine** [Icinga/icinga-powershell-framework#486]
If the icinga2 agent calls a command, the command will be displayed in icingaweb2. This is a problem, if there is a password in the command string. 

![image](https://user-images.githubusercontent.com/25454900/155103654-6b218edc-0791-4ddc-8d10-486afe8b290b.png)

## Expected Behavior
It would be nice, if the icingaweb2 would hide the password or the agent would have an option to hide commands on failure.
I think the best way is, that icingaweb2 would hide the password if the user has no admin permissions, so the admin has a chance to see the error and is able to debug the issue. Maybe you can use the protected custom variables (that is only an idea):
![image](https://user-images.githubusercontent.com/25454900/155105168-c75f3a71-0500-4930-98bd-cffec9af832f.png)

## Steps to Reproduce (for bugs)
1. Send a command to the agent with a password in it and let it fail. 

## Context
If a customer has read access to icingaweb2, the customer would be able to see the password if a command fails.

**Comment by LordHepipud** [comment]
This is already possible while using the Icinga configuration shipped by Icinga for Windows.

Icinga for Windows itself uses `SecureString` arguments, which are removed from any error output and replaced by a static input, preventing the password to show up. In addition, custom variables with name `*secure* and *securestring*` can be added to this list to prevent the variable being visible in Icinga Web 2.

The plugins shipped with Icinga 2 are deprecated and no longer maintained, as we no longer recommend using NSClient++, but Icinga for Windows instead.

**Comment by log1-c** [comment]
Hm, I had assumed that this would be something the Icinga 2 Agent / Core would need to handle. Regardless of the way it was installed or is being used.

**Comment by stevie-sy** [comment]
I think it's difficult to handle this in Icinga. Especially if the argument doesn't titled like "password" or "pwd" etc. Bash also doesn't have a type like SecureString as far I know. 

But what really works fine is the point with SecureString in PowerShell. @LordHepipud  did a great job to find a solution for our feature request https://github.com/Icinga/icinga-powershell-framework/issues/301 in the past.

**Comment by log1-c** [comment]
> think it's difficult to handle this in Icinga. Especially if the argument doesn't titled like "password" or "pwd" etc

I agree on that. but (I think) it could be quite easy to handle to _not_ print the whole command line to stdout which then appears as a check output in the webinterface.
Having the cmd line in the logs I don't see as critical as the webinterface output.

**Comment by LordHepipud** [comment]
But the output on the command line in case of an error is not Icinga related. That is on how the plugin is designed.
I don't think you could expect Icinga to check the output of the plugin, compare it to the arguments being used started messing around with it.

In my opinion, this problem relies entirely on the developer of the solution. Which is why I fixed this in #301 for Icinga for Windows, because you are right: Passwords should **never** be printed into the plugin output.

**Comment by log1-c** [comment]
You are correct, hadn't viewed it from that side.
I/We thought it was the output of the agent that couldn't even start the check command.

**Comment by LordHepipud** [comment]
I'm honestly not entire sure, on how the Agent handles this. In case the check command or file is not shown, you should simply get "Command not found" or "File not found" exceptions, but not the actual arguments on how it is called.

Atleast I never saw the Agent doing something like this before.

**Comment by LordHepipud** [comment]
I did some investigation on this. If a binary is not found on the system, the Agent will sadly print the entire command

```
Command "C:\Program Files\ICINGA2\/sbin/check_akcp_sensorprobeXplus" -h sales-net-hyperv.sales.demo -c public failed to execute: 2, "Das System kann die angegebene Datei nicht finden."
```

Which translates to `File not found on the system`

Sadly this is nothing Icinga for Windows can fix, the Agent is doing the bad stuff in this case. All PowerShell plugins are escaping the context properly and returning an output which is helpful to the user, while not printing password to the CLI.

To get this resolved, the best way would be to open a feature request/bug report for Icinga itself: https://github.com/Icinga/icinga2

The Icinga PowerShell team has sadly no way to fix this.
