### ISSUE TITLE
EventLogger-Feature is activated for agents with version < 2.13

### ISSUE THREAD

**Issue by RincewindsHat** [Icinga/icinga-powershell-framework#507]
## Expected Behavior
If an agent version < 2.13 is used (which does not have the EventLogger Feature, the Framework Installation shoud not try to use it (create corresponding file in `features-enabled`)

## Current Behavior
EventLogger is configured for versions < 2.13.

## Possible Solution
Check for the used Agent version during installation and do not try to activate features which are not present.

**Comment by LordHepipud** [comment]
Hello

Thank you for the issue. Honestly I don't understand it. Icinga for Windows is not enabling or disabling the EventLog feature of the Icinga Agent at all. This behavior is entirely done on the Icinga Agent side.

The only features we touch during installation are `checker`, `notification` and `api`: https://github.com/Icinga/icinga-powershell-framework/blob/master/lib/core/icingaagent/installer/Install-IcingaAgentBaseFeatures.psm1

The only function we actually *test* if the `windowseventlog` feature is enabled is at `Read-IcingaAgentLogFile`: https://github.com/Icinga/icinga-powershell-framework/blob/master/lib/core/icingaagent/readers/Read-IcingaAgentLogFile.psm1

There we check, if the feature is enabled and which version is used to either read the logs from file or from the EventLog.

What exactly is the problem you run into?

**Comment by RincewindsHat** [comment]
Ah ok, I thought the framework was responsible for (de-)activating features. In this case, it was an unfortunate chain of events where the latest version of the agent was installed and then removed without removing the configuration files properly.
After that the installation was initiated with als lower version again which didn't start due to the mischievous remaining config file
