### ISSUE TITLE
Custom Exception: InvalidNameSpace on most cluster- and hyperv-checks

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-framework#511]
The following problem affects all members of a single cluster:

```
icinga> invoke-icingacheckclusterhealth
[UNKNOWN]: Icinga Custom Error was thrown: Custom Exception: InvalidNameSpace

Custom exception occured:
No namespace with the specified name could be found on this system.
```

The following checks are affected:

```
Invoke-IcingaCheckClusterHealth
Invoke-IcingaCheckClusterSharedVolume
Invoke-IcingaCheckHyperVOverCommitment
Invoke-IcingaCheckHyperVSnapshot
Invoke-IcingaCheckHyperVVMHealth
```

I am not sure where this is coming from:

## Context

Looking at the code `Test-IcingaWindowsInformation` seems to detect a problem.
When I run the commandlet for all cluster-specific classes, I get the following output:

```
icinga> Test-IcingaWindowsInformation -ClassName MSCluster_Network -NameSpace 'Root\MSCluster';
1
icinga> Test-IcingaWindowsInformation -ClassName MSCluster_Resource -NameSpace 'Root\MSCluster';
16
icinga> Test-IcingaWindowsInformation -ClassName MSCluster_Node -NameSpace 'Root\MSCluster';
1
```

Running the following command in an admin powershell:

`icinga> get-ciminstance -ClassName MSCluster_Resource -NameSpace 'Root\MSCluster';`

.. brings the expected output, but at some point the following errir message is popping out:

```
get-ciminstance : Invalid property
At line:1 char:1
+ get-ciminstance -ClassName MSCluster_Resource -NameSpace 'Root\MSClus ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (Root\MSCluster:MSCluster_Resource:String) [Get-CimInstance], CimExceptio
   n
    + FullyQualifiedErrorId : HRESULT 0x80041031,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
```

Could this be the problem? Is something broken here?

## Your Environment

* PowerShell Version used (`$PSVersionTable.PSVersion`):

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  5066
```

* Operating System and version (`Get-IcingaWindowsInformation Win32_OperatingSystem | Select-Object Version, BuildNumber, Caption`):
```
Version    BuildNumber Caption
-------    ----------- -------
10.0.14393 14393       Microsoft Windows Server 2016 Datacenter
```

**Comment by LordHepipud** [comment]
Does this issue still exist after the latest bugfix releases?
On the other hand, if the CIM Manager is unable to fetch the information as the specified user, I would assume there is a problem on the host.

**Comment by K0nne** [comment]
The problem is gone without a trace. It seems it was a problem in the hosts.
