### ISSUE TITLE
Problem with service state in hyperv- and cluster-checks since 1.9.0

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-framework#517]
Hello!

We have updated to the latest releases. Since then all cluster- and hyperv-checks, which rely on the status of some services, don't wrk anymore:

The service in question is running.

Check: **Invoke-IcingaCheckHyperVOvercommitment**

![image](https://user-images.githubusercontent.com/34264690/167599259-1a0a29b7-6473-44e1-8fba-f1b74b609f79.png)

Check: **Invoke-IcingaCheckClusterHealth** 
The interesting thing here is, that service state 4 indicates "running".
![image](https://user-images.githubusercontent.com/34264690/167599503-0020615a-34e3-483b-9d51-f15af1c9358d.png)

## Expected Behavior
Service state can be fetched.

## Current Behavior
Service state is not available.

## Possible Solution
unknown

## Steps to Reproduce (for bugs)
Update from framework 1.8.0 and hyperv / cluster 1.0.0 to framework 1.9.0 hyperv / cluster 1.1.0

## Context
Icinga agent is running as .\LocalSystem. JEA is not used.

**Comment by LordHepipud** [comment]
Can you please test the linked PR on one system if it resolves the issue?
You just have to replace the `icinga-powershell-framework.psm1` inside the root folder from the one in the PR.

You do not require to rebuild a cache or something - just replace it and schedule the check in Icinga.
