### ISSUE TITLE
Problem with negative threshold range when using REST-API

### ISSUE THREAD

**Issue by dbecker1234** [Icinga/icinga-powershell-framework#528]
## Expected Behavior
An argument with negative threshold range should get passed to the check script no matter if Api-Check Forwarder is enabled or not.

## Current Behavior
When Api-Check Forwarder is enabled you get the following error message:

`Invalid range specified for threshold: InputValue "-0,​0299999993294477" and Threshold True`

## Steps to Reproduce (for bugs)

1. Configure a check using a negative threshold range as an argument. For example Invoke-IcingaCheckTimeSync:

`'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' '-NoProfile' '-NoLogo' '-ExecutionPolicy' 'ByPass' '-C' 'try { Use-Icinga -Minimal; } catch { Write-Output '\''The Icinga PowerShell Framework is either not installed on the system or not configured properly. Please check https://icinga.com/docs/windows for further details'\''; Write-Output '\''Error:'\'' $($_.Exception.Message)Components:`r`n$( Get-Module -ListAvailable '\''icinga-powershell-*'\'' )`r`n'\''Module-Path:'\''`r`n$($Env:PSModulePath); exit 3; }; Exit-IcingaExecutePlugin -Command '\''Invoke-IcingaCheckTimeSync'\'' ' '-Server' 'ntp.example.org' '-Warning' '-10:10' '-Critical' '-20:20' '-Verbosity' '2'`

2. Ensure that Api-Check Forwarder is enabled
3. You get the error message above
4. Disable Api-Check Forwarder: the check starts working
5. Use a positive threshold range for both -Warning and -Critical -> also working
6. Execute Invoke-IcingaCheckTimeSync directly in PowerShell -> works

## Your Environment

* PowerShell Version used (`$PSVersionTable.PSVersion`): 4.0

* Operating System and version (`Get-IcingaWindowsInformation Win32_OperatingSystem | Select-Object Version, BuildNumber, Caption`): Version: 6.3.9600, BuildNumber 9600, Server 2012 R2
But all version affected including newer systems.

**Comment by LordHepipud** [comment]
Can you please test the linked PR #550?
This should fix this issue.
