### ISSUE TITLE
The dedicated eventlog isnt't used

### ISSUE THREAD

**Issue by gkasKaR** [Icinga/icinga-powershell-framework#538]
Hello there,

with version 1.8, Icinga for Windows should write all its log entrys in the dedicated section of the eventlog.
The mentioned section was created but is still empty.

![Eventlog](https://user-images.githubusercontent.com/99650578/182811479-5929347a-66f7-484b-b857-c65a75019593.png)

Even with version 1.9.2 icinga writes its entrys in the application section :frowning:
It doesn't matter, which WinServ version I use.

Do you know what can fix this error? 🙂 

Thanks for your help!

**Comment by LordHepipud** [comment]
Thank you for the feedback. Have you tried to reboot the Windows machine?
In some cases, the EventLog gets confused and requires a reboot before anything is logged into the `Icinga for Windows` log, especially if the system was using the `Application` log before.

**Comment by gkasKaR** [comment]
Hello 🙂 

Thanks for your reply.
I was sure, that these systems rebooted in the last few weeks, but just to be safe I initianted a reboot a few minutes ago.
After that the Eventlog was still empty - Icinga writes its entrys in the application section 🙁

Is there another solution or approach to fix that?

Thank you very much!

**Comment by Skeletitor** [comment]
What i see on our installation: This eventlog (Icinga for Windows) ist only used by IfW Service. Icinga agent uses the Application log (Read-IcingaAgentLogFile->Application Log).

**Comment by LordHepipud** [comment]
Only Icinga PowerShell related tools will forward events to the EventLog inside the `Icinga for Windows` EventLog. This includes the PowerShell modules and the PowerShell service.

The Icinga Agent is separated from all of this and will log everything inside the `Application` EventLog. The Icinga for Windows team has no influence on this directly.
