### ISSUE TITLE
Install-IcingaFrameworkPlugins: Value cannot be null

### ISSUE THREAD

**Issue by weust1979** [Icinga/icinga-powershell-framework#54]
I have ran the "Install-Module icinga-powershell-plugins" and "Use-Icinga" Cmd-Lets, but "Install-IcingaFrameworkPlugins" throws me an error.
The following is on a fresh Windows Server 2019, fully patched, PS 5.1:

> PS C:\Users\Administrator> Install-IcingaFrameworkPlugins;
> Do you provide a custom repository for "Icinga Plugins"? (y/N):
> Which version to you want to install? (snapshot/stable) (Default: "stable"):
> Your "Icinga Plugins" is already up-to-date
> Exception calling "Format" with "2" argument(s): "Value cannot be null.
> Parameter name: args"
> At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\1.0.0\lib\core\framework\Install-IcingaFramew
> orkPlugins.psm1:10 char:5
> +     Write-Host ([string]::Format('Installing module into "{0}"', ($Ar ...
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
>     + FullyQualifiedErrorId : ArgumentNullException
> 
> Test-Path : Cannot bind argument to parameter 'Path' because it is null.
> At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\1.0.0\lib\core\framework\Expand-IcingaZipArch
> ive.psm1:8 char:20
> +     if ((Test-Path $Path) -eq $FALSE -Or (Test-Path $Destination) -eq ...
> +                    ~~~~~
>     + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom
>    mand
> 
> Exception calling "ExtractToDirectory" with "2" argument(s): "Empty path name is not legal."
> At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\1.0.0\lib\core\framework\Expand-IcingaZipArch
> ive.psm1:16 char:9
> +         [System.IO.Compression.ZipFile]::ExtractToDirectory($Path, $D ...
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : ArgumentException

Am I missing anything? I followed [02-installation](https://github.com/Icinga/icinga-powershell-plugins/blob/master/doc/02-Installation.md).

**Comment by LordHepipud** [comment]
Thank you very much - this issue was already fixed in #50 
The new version 1.0.1 released on Wednesday covers this fix as well. I would also recommend to do updates over PowerShell Gallery instead of the build-in update mechanism if PowerShell Gallery is the install source.

I havent tested if this is possible yet.

**Comment by weust1979** [comment]
Ah, ok. Think I saw #50 but interpreted it wrong.
