### ISSUE TITLE
Update-IcingaRepository - corrupts the own repositories file, if only a local folder is set

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icinga-powershell-framework#545]
During my tests with the new framework version I test also the new repo function. So I created a like described in the docs a new folder with the setup files like C:\Icinga\Setup. 

After run `New-IcingaRepository -Name Test -Path C:\Icinga\Setup` the expected JSON-file is excpected also with the hint that the the remote folder is set as the local folder
![image](https://user-images.githubusercontent.com/38723488/185206049-42128d0a-a384-4144-afcf-0572c5c324c3.png)

This is the JSON:
```
{
    "Info":  {
                 "LocalSource":  "C:\\Icinga\\Setup",
                 "RemoteSource":  "C:\\Icinga\\Setup",
                 "Created":  "2022/08/17 17:39:00",
                 "Updated":  "2022/08/17 17:39:00",
                 "RepoHash":  "086ACF9D81E483E24B3D2FDE62344F12CC2AAE6499E20914CF3C103E38787193"
             },
    "Packages":  {
                     "agent":  [
                                   {
                                       "Hash":  "CBC9447FD704910952731E9BCC979D5729906F1AA122C822583C38F2D1DF60EE",
                                       "Location":  "\\Icinga2-v2.13.5-x86_64.msi",
                                       "RelativePath":  true,
                                       "Version":  "2.13.5",
                                       "Snapshot":  false,
                                       "Architecture":  "x64"
                                   }
                               ]
                 }
}
```

After running `Update-IcingaRepository -Name 'Test'` the Info Part of the JSON is changed to this.
```
"Info":  {
                 "LocalSource":  "C:\\Icinga\\Setup\\",
                 "RemoteSource":  "",
                 "Created":  "2022/08/17 17:40:33",
                 "Updated":  "2022/08/17 17:40:33",
                 "RepoHash":  "086ACF9D81E483E24B3D2FDE62344F12CC2AAE6499E20914CF3C103E38787193"
             },
```
As you can see, "RemoteSource" is empty now. 

With the result that the Cmdlet `Install-Icinga` throws an error with the URL:
![image](https://user-images.githubusercontent.com/38723488/185206659-4cec4670-c334-4941-8dd0-c6e4c017d705.png)

**Comment by LordHepipud** [comment]
Thanks - fixed with v1.10.0 and inside the current master!
