### ISSUE TITLE
Install-Icinga - missing parameter AnswerFile (described in the docs), instead InstallFile exist

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icinga-powershell-framework#546]
According to the docs (https://icinga.com/docs/icinga-for-windows/latest/doc/110-Installation/04-Installation-Templates/) there are existing to paramter for the Cmdlet "Install-icinga":
-InstallCommand 
-AnswerFile

But in the ISE e.g. only offers this
![image](https://user-images.githubusercontent.com/38723488/185209912-1608e41c-0b85-4d3a-94fe-2711a07d696f.png)

looking at the code there is no definition for the param AnswerFile
```
function Install-Icinga()
{
    param (
        [string]$InstallCommand = $null,
        [string]$InstallFile    = ''
...
```

So maybe the paramter InstallFile is named wrong or the docs are wrong. But the param InstallFile has that beavior what you described for AnswerFile ;-)

**Comment by LordHepipud** [comment]
Thank you! Yes, the docs are wrong in this case as the argument is `-InstallFile` to match the `-InstallCommand` argument.
