### ISSUE TITLE
Ticket CURL ERROR Operation timed out after 3000 milliseconds when using SelfServiceAPIKey with Start-IcingaAgentInstallWizard

### ISSUE THREAD

**Issue by t-rex2** [Icinga/icinga-powershell-framework#56]
When using the Start-IcingaAgentInstallWizard routine with parameter **SelfServiceAPIKey** an issue appears.

```
Start-IcingaAgentInstallWizard -UseDirectorSelfService 1 -DirectorUrl https://monitoring/icingaweb2/director -AddFirewallRule True -AcceptConnections True **-SelfServiceAPIKey** '214a8db9e1a9f7906afecb0765a0274922a13986' -EmptyTicket 1 -InstallFrameworkPlugins 1 -PluginsUrl 'https://monitoring/icinga2-agent/icinga-powershell-plugins.zip'-InstallFrameworkService 1 -FrameworkServiceUrl 'https://monitoring/icinga2-agent/icinga-service-v1.0.0.zip' -ServiceDirectory 'C:\Program Files\Icinga-Framework-Service\' -ServiceBin 'C:\Program Files\Icinga-Framework-Service\icinga-service.exe' -RunInstaller
```

It seems that the parameter **ticket** isn't filled correctly (with the API Key). This is the output:

> Failed to create certificate.
> Arguments: pki request --host ICINGA.domain.test --port 5665 --ticket @{error=CURL ERROR: Operation timed out after 3000 milliseconds with 0 out of 0 bytes received} --key C:\ProgramData\icinga2\var\lib\icinga2\certs\SERVER.domain.test.key --cert C:\ProgramData\icinga2\var\lib\icinga2\certs\SERVER.domain.test.crt --trustedcert C:\ProgramData\icinga2\var\lib\icinga2\certs\trusted-parent.crt --ca C:\ProgramData\icinga2\var\lib\icinga2\certs\ca.crt
>  rror:critical/cli: Too many arguments. At most 0 arguments may be specified.
> Failed to sign Icinga certificate
> At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\lib\core\icingaagent\installer\Install-IcingaAgentCertificates.psm1:81 char:17
>                  throw 'Failed to sign Icinga certificate';
>                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : OperationStopped: (Failed to sign Icinga certificate:String) [], RuntimeException
>      FullyQualifiedErrorId : Failed to sign Icinga certificate

## Expected Behavior
The routine of Start-IcingaAgentInstallWizard should set the parameter **SelfServiceAPIKey** to the corresponding powershell code.

## Current Behavior
If using the parameter **SelfServiceAPIKey** with Start-IcingaAgentInstallWizard is seems not to be mapped to the ticket parameter in the powershell code.
Despite the error message the installation of icinga2-agent was done, but the icinga2-agent is getting into trouble because of missing ca.cert. So the communication between icinga2-agent and icinga2-server doesn't work.

## Possible Solution
I'm not sure if this is a bug-fix or a dirty workaround. ;)
When the $Ticket gets the value of $SelfServiceAPIKey the installation is running successfully to the end. Line 74 is the current status and line 75 the workaround.

C:\Program Files\WindowsPowerShell\Modlues\icinga-powershell-framework\lib\core\icingaagent\misc\Start-IcingaAgentInstallWizard.psm1
74             $Ticket              = $Result.Value;
75             $Ticket              = $SelfServiceAPIKey

## Steps to Reproduce (for bugs)
Following the whole output from the powershell console:
> PS C:\Windows\system32> Use-Icinga
> PS C:\Windows\system32> Start-IcingaAgentInstallWizard -UseDirectorSelfService 1 -DirectorUrl https://monitoring/icingaweb2/director -AddFirewallRule True -AcceptConnections True -SelfServiceAPIKey '214a8db9e1a9f7906afecb0765a0274922a13986' -EmptyTicket 1 -InstallFrameworkPlugins 1 -PluginsUrl 'https://monitoring/icinga2-agent/icinga-powershell-plugins.zip'-InstallFrameworkService 1 -FrameworkServiceUrl 'https://monitoring/icinga2-agent/icinga-service-v1.0.0.zip' -ServiceDirectory 'C:\Program Files\Icinga-Framework-Service\' -ServiceBin 'C:\Program Files\Icinga-Framework-Service\icinga-service.exe' -RunInstaller
> Host was successfully registered within Icinga Director
> Using hostname "SERVER.domain.test" for the Icinga 2 Agent configuration
> Downloading "Icinga Plugins" into "C:\Users\USERNAME\AppData\Local\Temp\tmp_icinga1994808586.d"
> Installing module into "C:\Users\USERNAME\AppData\Local\Temp\tmp_icinga1994808586.d"
> Using content of folder "C:\Users\USERNAME\AppData\Local\Temp\tmp_icinga1994808586.d\icinga-powershell-plugins-master" for updates
> Plugin Module Directory "C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins" is not present. Creating Directory
> Copying files to plugins
> Cleaning temporary content
> Unblocking Icinga PowerShell Files
> Icinga Plugin update has been completed
> The wizard is complete. These are the configured settings:
> -UseDirectorSelfService 1
> -DirectorUrl https://monitoring/icingaweb2/director
> -SelfServiceAPIKey 214a8db9e1a9f7906afecb0765a0274922a13986
> -AddFirewallRule True
> -AcceptConnections True
> -AddFirewallRule True
> -AcceptConnections True
> -Ticket '@{error=CURL ERROR: Operation timed out after 3000 milliseconds with 0 out of 0 bytes received}'
> -EmptyTicket 1
> -InstallFrameworkPlugins 1
> -PluginsUrl 'https://monitoring/icinga2-agent/icinga-powershell-plugins.zip'
> -RunInstaller
> Start-IcingaAgentInstallWizard -UseDirectorSelfService 1 -DirectorUrl https://monitoring/icingaweb2/director -SelfServiceAPIKey 214a8db9e1a9f7906afecb0765a0274922a13986 -AddFirewallRule True -AcceptConnections True -AddFirewallRule True -AcceptConnections True -Ticket '@{error=CURL ERROR: Operation timed out after 3000 milliseconds with 0 out of 0 bytes received}' -EmptyTicket 1 -InstallFrameworkPlugins 1 -PluginsUrl 'https://monitoring/icinga2-agent/icinga-powershell-plugins.zip' -RunInstaller
> Downloading Icinga 2 Agent installer "Icinga2-v2.11.3-x86_64.msi" into temp directory "C:\Users\USERNAME\AppData\Local\Temp\Icinga2-v2.11.3-x86_64.msi"
> Installing new Icinga Agent version into "C:\Program Files\ICINGA2"
> Icinga Agent was successfully installed
> Successfully backed up Icinga 2 Agent default config
> Your hostname was successfully changed to "SERVER.domain.test"
> The Icinga Service User already has permission to run as service
> [PASSED]: Directory "C:\ProgramData\icinga2\etc" is accessible and writeable by the Icinga Service User "NT AUTHORITY\NetworkService"
> [PASSED]: Directory "C:\ProgramData\icinga2\var" is accessible and writeable by the Icinga Service User "NT AUTHORITY\NetworkService"
> [PASSED]: Directory "C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\cache" is accessible and writeable by the Icinga Service User "NT AUTHORITY\NetworkService"
> Service User successfully updated
> Updating Icinga PowerShell Service binary
> The Icinga PowerShell Service is already installed
> Service User successfully updated
> Restarting service "icingapowershell"
> Service User successfully updated
> Background daemon Cmdlet "Start-IcingaServiceCheckDaemon" has been configured
> Feature "checker" was successfully disabled
> Feature "api" was successfully enabled
> Generating host certificates for host "SERVER.domain.test"
> information/base: Writing private key to 'C:\ProgramData\icinga2\var\lib\icinga2\certs\SERVER.domain.test.key'.
> information/base: Writing X509 certificate to 'C:\ProgramData\icinga2\var\lib\icinga2\certs\SERVER.domain.test.crt'.
> Your trusted master certificate is not present. Fetching from your CA server is required
> Fetching trusted master certificate from "ICINGA.domain.test"
> information/cli: Retrieving X.509 certificate for 'ICINGA.domain.test:5665'.
>  Subject:     CN = ICINGA.domain.test
>  Issuer:      CN = Icinga CA
>  Valid From:  Oct 20 11:02:17 2016 GMT
>  Valid Until: Oct 17 11:02:17 2031 GMT
>  Fingerprint: 1C AB 1D 2A 84 77 AB 6D 4E 7A 7B A5 74 35 0C 44 B9 1C 62 47
> ***
> *** You have to ensure that this certificate actually matches the parent
> *** instance's certificate in order to avoid man-in-the-middle attacks.
> ***
> information/pki: Writing certificate to file 'C:\ProgramData\icinga2\var\lib\icinga2\certs\trusted-parent.crt'.
> Your ca.crt is not present. Manuall copy or fetching from your Icinga CA is required.
> Failed to create certificate.
> Arguments: pki request --host ICINGA.domain.test --port 5665 --ticket @{error=CURL ERROR: Operation timed out after 3000 milliseconds with 0 out of 0 bytes received} --key C:\ProgramData\icinga2\var\lib\icinga2\certs\SERVER.domain.test.key --cert C:\ProgramData\icinga2\var\lib\icinga2\certs\SERVER.domain.test.crt --trustedcert C:\ProgramData\icinga2\var\lib\icinga2\certs\trusted-parent.crt --ca C:\ProgramData\icinga2\var\lib\icinga2\certs\ca.crt
>  rror:critical/cli: Too many arguments. At most 0 arguments may be specified.
> Failed to sign Icinga certificate
> At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\lib\core\icingaagent\installer\Install-IcingaAgentCertificates.psm1:81 char:17
>                  throw 'Failed to sign Icinga certificate';
>                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : OperationStopped: (Failed to sign Icinga certificate:String) [], RuntimeException
>      FullyQualifiedErrorId : Failed to sign Icinga certificate

## Your Environment
The powershell version is:
Major 5, Minor 1, Build 14393, Revision 3383

OS: Windows Server 2016 Standard
Version: 10.0.14393

**Comment by LordHepipud** [comment]
Thank you for the detailed report!

There is a difference between the `Ticket` and the `SerlfServiceAPIKey`. Last one is to authenticate on the Icinga Director to fetch information on how the Agent should be configured. This will also include the `Ticket` for signing the certificate requests.

A weird issue here is, that your ticket is containing the content

```
@{error=CURL ERROR: Operation timed out after 3000 milliseconds with 0 out of 0 bytes received}
```

which indicates the Director was unable to connect to your Icinga 2 node (my assumption for the moment). As it seems the Director is not itself causing a server error for this, the module is being executed because there are not checks implemented to *validate* the content in full detail.

I will try to dig a little deeper into this case, as I was unable to reproduce it yet. Which PowerShell Framework version do you have installed at the moment?

**Comment by t-rex2** [comment]
**Icinga Powershell Framwork 1.0.1**

Some more information to the Icinga2-Server:
SLES 12 SP4

With the following Icingaweb2 modules:
director | 1.7.2
fileshipper | 1.1.0
incubator | 0.5.0
ipl | v0.3.0
monitoring | 2.7.3
pnp | 1.1.0
reactbundle | 0.7.0
vspheredb | 1.1.0

**Comment by LordHepipud** [comment]
I played around a little with the configuration and plenty of different tasks and sadly I was unable to reproduce the error within my environment.

My assumption is, that the Director is not able to fetch the Ticket for signing the certificate properly. Your workaround will simply ensure that the certificates are not using the Ticket (which is wrong anyway) and therefor you have to sign the certificate manually on the Icinga 2 CA master - correct?

I'm wondering however, on why the Director is not able to talk to the Icinga 2 API and is unable to fetch the ticket.
