### ISSUE TITLE
icinga -RebuildCache - add option to not start the IMC afterwards

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icinga-powershell-framework#573]
For rebuilding the Code Cache there exists the param `-RebuildCache`. Afterwards the IMC is started. But for automation - like sending this Cmdlet to every/some/many server(s) via WinRM this is not so fine. 
For this action it would be very helpful if there is an additional option to don't start the IMC or to have an another cmdlet for such tasks. 

I saw there exists the cmdlet `Write-IcingaFrameworkCodeCache` but it looks like it doesn't the same. e.g. if you install the PowerShell-moduls manully, `icinga -RebuildCache` is also doing some migration tasks if necessary

**Comment by LordHepipud** [comment]
Thank you for the issue. Basically you want to do the following two steps:

```powershell
Invoke-IcingaForWindowsMigration;
Write-IcingaFrameworkCodeCache;
```

This will however not update the current PowerShell instance, as the module is already loaded. Therefor the full handling would be:

```powershell
# Reset all cache files, including installed plugins
Copy-IcingaFrameworkCacheTemplate
# Update Framework Cache
Write-IcingaFrameworkCodeCache;
# Remove the global variable Icinga, to reset possible invalid states
Remove-Variable -Name 'Icinga' -Scope 'Global' -ErrorAction 'SilentlyContinue'
# Re-Import the entire Framework to apply changes
Import-Module 'icinga-powershell-framework' -Force;
Import-Module 'icinga-powershell-framework' -Global -Force;
# Apply migrations
Invoke-IcingaForWindowsMigration;
```

and after that your entire code.

We could implement yet another flag doing all these things for the user. but would I'm not sure about a suitable name and the benefit for the moment. Suggestions?

**Comment by LordHepipud** [comment]
Well, what I mostly do at the moment is something like this

```powershell
icinga -RebuildCache { Write-IcingaConsoleNotice 'Loading Icinga Shell' };
```

Because you can call ScriptBlocks which just checks if something was set and is executed. A simple `Write-Host` would be enough.

**Comment by stevie-sy** [comment]
Thanks, works also fine. Maybe then is a small chapter (e.g. for automation with own tools) in the docs enough?!?

**Comment by tbauriedel** [comment]
ref/NC/761567
