### ISSUE TITLE
Start-IcingaAgentInstallWizard stops with 404 failure

### ISSUE THREAD

**Issue by blindzero** [Icinga/icinga-powershell-framework#58]
Hi,
after trying the self-service endpoint wizard (which didn't work, will file another case for this afterwards), I tried the manual way.
After answering all the questions (mostly with accept defaults, no custom repositories) the following command was created:

```
Start-IcingaAgentInstallWizard -UseDirectorSelfService 0 -AutoUseFQDN 1 -AutoUseHostname 0 -LowerCase 1 -UpperCase 0 -PackageSource 'https://packages.icinga.com/windows/' -AllowVersionChanges 1 -AgentVersion 'latest' -Endpoints icinga2.FQDN.DOMAIN.TLD -CAPort 5665 -AcceptConnections 1 -AddFirewallRule 1 -EndpointConnections [icinga2.FQDN.DOMAIN.TLD]:56
65 -ParentZone master -AddDirectorGlobal 1 -AddGlobalTemplates 1 -GlobalZones @() -CAEndpoint icinga2.FQDN.DOMAIN.TLD  -EmptyTicket 0 -Ticket 'LONGTICKETTOKENTAKENFROMDIRECTORPAGE' -ServiceUser 'NT Authority\NetworkService' -InstallFrameworkPlugins 1 -PluginsUrl 'https://github.com/Icinga/icinga-powershell-plugins/archive/v1.0.0/v1.0.0.zip' -InstallFrameworkService 1 -FrameworkServiceUrl 'https://github.com/Icinga/icinga-powershell-service/releases/download/v1.0.0/icinga-service-v1.0.0.zip' -ServiceDirectory 'C:\Program Files\icinga-framework-service\' -ServiceBin 'C:\Program Files\icinga-framework-service\icinga-service.exe' -RunInstaller
```

This terminates with the following error:
```
Downloading Icinga 2 Agent installer "Icinga2-v2.12.0rc1-x86_64.msi" into temp directory "C:\Users\user\AppData\Local\Temp\Icinga2-v2.12.0rc1-x86_64.msi"
Unable to load the module. Please check your PowerShell execution policies for possible problems. Error: System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
   bei Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   bei Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
```

I am running on Windows Server 2016 with $PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.3471
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3471
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

I just invoked the Kickstart Scrip from website's documentation.

**Comment by LordHepipud** [comment]
The problem is that the package is not present on `packages.icinga.com`

The script is looking up `Icinga2-v2.12.0rc1-x86_64.msi` while the correct name is `Icinga2-v2.12.0-rc1-x86_64.msi`. Thats why a 404 is returned.

Im curious - did this work with the old module?

**Comment by blindzero** [comment]
@LordHepipud 
Well, I always used the kickstart PS1 script from director's web frontend...this performed so far (besides the stability issues, which was the main reason why I want to check new framework).

Trying to change the package source with full path manually didn't work either:
Start-IcingaAgentInstallWizard -UseDirectorSelfService 0 -AutoUseFQDN 1 -AutoUseHostname 0 -LowerCase 1 -UpperCase 0 -PackageSource 'https://packages.icinga.com/windows/Icinga2-v2.12.0-rc1-x86_64.msi' -AllowVersionChanges 1 -AgentVersion 'latest' -Endpoints icinga2.FQDN.DOMAIN.TLD -CAPort 5665 -AcceptConnections 1 -AddFirewallRule 1 -EndpointConnections [icinga2.FQDN.DOMAIN.TLD]:5665 -ParentZone master -AddDirectorGlobal 1 -AddGlobalTemplates 1 -GlobalZones @() -CAEndpoint icinga2.FQDN.DOMAIN.TLD -EmptyTicket 0 -Ticket 'LONGTICKETFROMDIRECTOR' -ServiceUser 'NT Authority\NetworkService' -InstallFrameworkPlugins 0 -InstallFrameworkService 0 -RunInstaller
====
No Icinga installation MSI package for your architecture could be found for the provided version and source In C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\lib\core\icingaagent\getters\Get-IcingaAgentMSIPackage.psm1:59 Zeichen:9
+         throw 'No Icinga installation MSI package for your architectu ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (No Icinga insta...sion and source:String) [], RuntimeException
    + FullyQualifiedErrorId : No Icinga installation MSI package for your architecture could be found for the provided version and source

**Comment by LordHepipud** [comment]
Thank you very much! The problem is the package source is only the path on where to locate the MSI installer package. The remaining part for which version should be installed is constructed by the module itself.

As far as I can tell (have no test system here right now), you will simply have to set the version to install inside the Self-Service API to

```
2.12.0-rc1
```

By using the default source (packages.icinga.com) you should see a successful installation. The rest of the naming

```
Icinga2-v{version}-x86_64.msi
```

is build automatically. Does this work?

**Comment by blindzero** [comment]
@LordHepipud ok, using dedicated version 2.11.0 instead of latest works out.

Besides that interesting that the manual agent installation (not using self-service endpoint) solves my issue from #59.

**Comment by LordHepipud** [comment]
Wait, by using 'latest' inside the self-service you will get 2.12.0-rc1 !?
You shouldn't get a RC version at all by using 'latest', only the latest stable.

**Comment by blindzero** [comment]
Sorry for being not detailed enough ;)

The problem occurs when using the default "latest" as input or "2.12.0-rc1" as you mentioned above.
Using 2.11.0 manually works out.

**Comment by LordHepipud** [comment]
Yeah, funny. The module is fetching the wrong version for `latest`

```powershell
Get-IcingaAgentMSIPackage -Source https://packages.icinga.com/windows -Version latest -SkipDownload;
```

```powershell
Name                           Value
----                           -----
InstallerPath
Version                        2.12.0rc1
LastUpdate                     20200313
```

This should not happen at all.... I will have a look on why and provide a fix. Thank you for the report!
