### ISSUE TITLE
[feature request] create own snapshot repo

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icinga-powershell-framework#587]
With `New-IcingaRepository` is it possible to create own repositories. But they are always defined as "stable" repo. There is no switch available to say the cmdlet that the new repo is a snapshot repo. You can only edit the new json file. But with the `Sync-IcingaRepository` it is again a stable repo. 

This would be important if we want to use - e.g. for test environment - the snapshot repos. And as default behavior and for security reasons our servers have no access to the internet. 

Especially for a test and development environment a staging is very usful. If this would be possible, We could use also the param _-Snapshot_ with every other existing repo cmcllet. 

As workarround we created diffrent "stable"-repos. And depending on the kind of server, we assign and activate the repo. A bit cumbersome, but it's possible.

**Comment by carraroj** [comment]
ref/NC/764912

**Comment by LordHepipud** [comment]
That's a great idea. I will add this to v1.12.
