### ISSUE TITLE
 Invoke-IcingaCheckDiskHealth broken in v.1.10.0

### ISSUE THREAD

**Issue by geotekberlin** [Icinga/icinga-powershell-framework#588]
After upgrading Powershell Framework and Plugins to v.1.10.0 the Invoke-IcingaCheckDiskHealth throws an error:

```
PS C:\> Invoke-IcingaCheckDiskHealth
[UNKNOWN]: Icinga Invalid Input Error was thrown: ConversionUnitMissing

Unable to parse input value. You have to add an unit to your input value. Example: "10GB". Allowed units are: "B, KB, MB, GB, TB, PB, KiB, MiB, GiB, TiB, PiB".
Ausnahme beim Aufrufen von "Compile" mit 0 Argument(en):  "Ausnahme beim Aufrufen von "Compile" mit 0 Argument(en):  "Ausnahme beim Aufrufen von "Compile" mit 0 Argument(en):  "Ausnahme
beim Aufrufen von "Compile" mit 0 Argument(en):  "Ausnahme beim Aufrufen von "__CreateDefaultThresholdObject" mit 0 Argument(en):  "Systemfehler"""""
In C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\cache\framework_cache.psm1:28116 Zeichen:16
+         return $IcingaCheckResult.Compile();
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ScriptMethodRuntimeException

Check
-----
@{Name=Physical Disk Package; Verbose=0; __CheckPerfData=System.Collections.Hashtable; __Hidden=False; __Parent=; __Indention=0; __ErrorMessage=; __CheckState=0; __CheckCommand=Invoke-...
```
Calling **icinga -RebuildCache** and **Write-IcingaFrameworkCodeCache** did not help. All other plugins continue to work as expected.

**Comment by puseidr** [comment]
i've tried your PR but in my case it didnt fixed the problem. and it also messed up other checks like "Invoke-IcingaCheckNetworkInterface"
which results in an error like this:

```
[UNKNOWN] Icinga Exception: Ausnahme beim Aufrufen von "WarnIfMatch" mit 1 Argument(en):  "Ausnahme beim Aufrufen von "WarnIfLike" mit 1 Argument(en):  "Der Wert "425.984Mbit" kann nicht in den Typ "System.Decimal" konvertiert werden. Fehler: "Die Eingabezeichenfolge hat das falsche Format."""
CheckCommand: Invoke-IcingaCheckNetworkInterface Arguments: System.Collections.Hashtable StackTrace: bei Get-IcingaNetworkSpeedChecks, C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\compiled\icinga-powershell-plugins.ifw_compilation.psm1: Zeile 9332 bei Invoke-IcingaCheckNetworkInterface, C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\compiled\icinga-powershell-plugins.ifw_compilation.psm1: Zeile 2549 bei Exit-IcingaExecutePlugin, C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\cache\framework_cache.psm1: Zeile 26462 bei , : Zeile 1
```

**Comment by Marci24h** [comment]
i checked out the commit: [92a56994633f6e0e4ca90c2169ae8c7e07cbbef1](https://github.com/Icinga/icinga-powershell-framework/pull/589/commits/92a56994633f6e0e4ca90c2169ae8c7e07cbbef1) and for me it works.
Bevore i got the [UNKNOWN] Result and now it is [OK].
After replacing the Files, i clear the framework cache.
@puseidr have you tried to clear the framework cache.

**Comment by puseidr** [comment]
i've edited the 2 files and than used "Write-IcingaFrameworkCodeCache"

**Comment by Marci24h** [comment]
i've done it like it is mentioned in [IWKB000014](https://icinga.com/docs/icinga-for-windows/latest/doc/knowledgebase/IWKB000014/)

Clear Cache:
- stop Services (icinga2 & icingapowershell)
- copy the File: `c$\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\templates\framework_cache.psm1.template` over `c$\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\cache\framework_cache.psm1`
- start Services (icinga2 & icingapowershell)

**Comment by geotekberlin** [comment]
Unfortunately, replacing the two files and resetting the framework cache did not solve the issue for me either.

**Comment by LordHepipud** [comment]
I checked the network plugin and you are right, this one is broken with the PR.
I will fix that by updating the PR with a new version shortly.

**Comment by Marci24h** [comment]
i can confirm.
for me the network plugin also is broken.

**Comment by geotekberlin** [comment]
I don't want to push, but I am eagerly awaiting a fix. Is there any progress yet?

**Comment by LordHepipud** [comment]
Can you please test the updated PR? This issue and the newly introduced one should be resolved now.

Release is planned for December including other issues currently open.

**Comment by puseidr** [comment]
the PR fixed the issue on all my affected systems
good job :)

**Comment by geotekberlin** [comment]
The last PR fixed my issues as well. Thanks!
