### ISSUE TITLE
can´t connect with Start-IcingaAgentInstallWizard to selfservice api

### ISSUE THREAD

**Issue by nobe80** [Icinga/icinga-powershell-framework#594]
Hi,

i am using powershell to connect to icinga2 selfservice API but each try leads to "Failed to connect"

```
[Error]: Failed to connect to your Icinga Director at "https://<fqdn>/icingaweb2/director/". Please try again
Please re-enter your SelfService API Key for the Host-Template in case the key is no longer assigned to your host (Defaults: "29d00071d3009d04e19babe989b7138d58d3xxxxx"):
```

When i try Get-IcingaDirectorSelfServiceConfig:
```
Get-IcingaDirectorSelfServiceConfig -DirectorUrl https://fqdn/icingaweb2/director/ -ApiKey 29d00071d3009d04e19babe989b7138d58d3xxxx
```

leads to: 
```
ConvertFrom-Json : Ungültiger JSON-Primitiv: .
In C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\1.8.0\cache\framework_cache.psm1:72 Zeichen:20
+     $JsonContent = ConvertFrom-Json -InputObject $response.Content;
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

How is the best way to get more infos about the issue? 
Can this something to do with the ssl certificate? 

regards

**Comment by LordHepipud** [comment]
Is the certificate self-signed or signed by a trusted publisher? What happens if you open a browser on this machine and try to access Icinga Web? Is there an SSL error or do you get through instantly?

**Comment by nobe80** [comment]
I forget to add the icinga information of our server:

    Director version (System - About): 1.9.1
    Icinga Web 2 version and modules (System - About): 2.11.2
    Icinga 2 version (icinga2 --version): r2.13.6-1
    Operating System and version: Debian 11
    Webserver, PHP versions:Apache, PHP 8.1

The Webserver certificate is created by Letsencrypt without any issues. We reach the Director webinterface with no problems. 

Can it be that the API has its own certificate? This we created with icinga2 api setup and the CN of this certificate is not equal like the Webserver HTTPS certificate. Can this something to do with this error? Or has the enpoint name like the fqdn ?
Is there any logfile in Powershell framework to see little bit more?

**Comment by LordHepipud** [comment]
For this step there is no entry inside the EventLog, as the error message itself should catch all the errors and depending on the output print a helping information.
I'm not sure on why there is a JSON error on the Icinga Director API output. I will have to do some testing there.

**Comment by LordHepipud** [comment]
To answer your question: The certificate for the Icinga Director is the one from the Apache web server. The Icinga CA is not used i this case.
What happens if you use the template Agent key? You should receive an output like this:

```powershell
Get-IcingaDirectorSelfServiceConfig -DirectorUrl https://..../icingaweb2/director -ApiKey fh4j88258228452126454694ej14944k00j7b4b7
```

```
fetch_agent_name          : True
fetch_agent_fqdn          : False
transform_hostname        : 1
flush_api_directory       : False
resolve_parent_host       : 0
install_framework_service : 0
install_framework_plugins : 0
director_host_object      : {"address":"&ipaddress&","display_name":"&fqdn.lowerCase&"}
IcingaMaster              : icingamaster.demo.icinga.com
```

**Comment by nobe80** [comment]
Response of that:
![powershell_icinga2_response](https://user-images.githubusercontent.com/66213908/203259570-7b64e00f-7210-4a8b-ad09-8cc4bb6da20f.PNG)

**Comment by LordHepipud** [comment]
And there is the problem. The Icinga Director is printing a deprecation warning which is preventing the JSON Converter to properly convert the result.
I assume updating the Icinga Director and/or PHP might resolve this issue.

**Comment by nobe80** [comment]
Thank you.

I guess updating to director 1.10.2 would be the solution because PHP is already 8.1 
I try that and give a feedback

**Comment by nobe80** [comment]
Hi,

after the update to the newest director version the error is gone. The Version now shows "master". Do you know how to change that to show the version number?

<img width="724" alt="Bildschirmfoto 2022-11-23 um 16 06 44" src="https://user-images.githubusercontent.com/66213908/203581195-14c4a321-f9d5-43c4-84e0-337c2bb5a7b9.png">

**Comment by RincewindsHat** [comment]
@LordHepipud  Sounds like "solved" to me
