### ISSUE TITLE
Invoke-IcingaCheckFirewall: No checks added to this package

### ISSUE THREAD

**Issue by Kaliumiodid** [Icinga/icinga-powershell-framework#599]
On the Windows servers in my environment, I check if the firewall in all profiles is enabled and get an error if not.
Since I updated to version 1.10 on one server, the local execution is fine but executing it remotely, I get the state Unknown and the text says "No checks added to this package". I didn't made any changes in the host configuration and copy pasted the CheckCommand config provided here. In the service configuration I have these two lines:

`vars.IcingaCheckFirewall_Array_Profile = [ "Public","Private","Domain" ]`
`vars.IcingaCheckFirewall_Switchparameter_Enabled = true`

The same config worked in version 1.9.

**Comment by LordHepipud** [comment]
Found the issue. Fixed with v1.10.1
