### ISSUE TITLE
Invoke-IcingaCheckService - Service Exclusion

### ISSUE THREAD

**Issue by pakyg** [Icinga/icinga-powershell-framework#603]
Hello,
through the "-Exclude" parameter I can't exclude all the services that start with the same name.
Example: "Invoke-IcingaCheckService -Exclude 'CDPUserSvc_*' -Status 'Running' -FilterSta
rtupType 'Automatic' -Verbosity 3"

![image](https://user-images.githubusercontent.com/70367256/210773013-5f71357f-4b89-45a4-804f-ef7c1d6188a1.png)
How can I exclude n. services by setting the asterisk to take them all?

Thanks,
Greetings

**Comment by drapiti** [comment]
> 

Hi @LordHepipud, this was accidentally closed because there was a service remediation active which was making it seem as if the services had been excluded but rather they were excluded because they were up and running again not beacuase the filter was working.
Cheers.

**Comment by LordHepipud** [comment]
That makes sense. Thanks for the input!
Can you test the linked PR please? this should now work fine.

**Comment by drapiti** [comment]
> That makes sense. Thanks for the input! Can you test the linked PR please or the v1.11.0 master? This should now work fine.

will do.

**Comment by drapiti** [comment]
Hi @LordHepipud I can confirm the fix is working for us. 
Thanks
