### ISSUE TITLE
The Start-IcingaAgentInstall Command provided by the FrameWorkWizard has some Bugs

### ISSUE THREAD

**Issue by iiM-Dawnbreaker** [Icinga/icinga-powershell-framework#61]
The Start-IcingaAgentInstallWizard with Parameters provided by the FrameWorkWizard has some Mistakes in it.

Running the FrameWorkWizard on Version 1.0.1 results in following unattended command:

```
Start-IcingaAgentInstallWizard -UseDirectorSelfService 1 -DirectorUrl http://mm-v01/icingaweb2/director -SelfServiceAPIKey 6ffc784669417fa34be89133adff6
ec4a8b0525c -AddFirewallRule True -AcceptConnections True -AddFirewallRule True -AcceptConnections True -Ticket 'a52754820263e87727b11bb38c6af4ac0d41f8d
8' -EmptyTicket 1 -InstallFrameworkPlugins 1 -PluginsUrl 'https://github.com/Icinga/icinga-powershell-plugins/archive/v1.0.0/v1.0.0.zip' -RunInstaller
```

But it has the -AddFirewallRule and the -AcceptConnections Paramter twice in it.
Also the DirectorUrl and the SelfServiceApiKey has to be in quotes.

**Comment by LordHepipud** [comment]
Thank you very much for the feedback! I will have a look on the duplicate arguments. For the string part, ye, this should be resolved but in general this shouldn't affect the arguments in it as long as no whitepace is included.

Still, this need to be fixed. Thank you a lot!
