### ISSUE TITLE
Invoke-IcingaCheckProcess Error processing performance data

### ISSUE THREAD

**Issue by drapiti** [Icinga/icinga-powershell-framework#617]
The following error is presented with the Invoke-IcingaCheckProcess using the latest framerwork:
_Icinga Exception: Unable to process transformation of arguments in parameter 'NoPerfData'. Cannot convert value 'System.String' to type 'System.Management.Automation.SwitchParameter'. Boolean parameters accept only Boolean values ​​and numbers, such as $True, $False, 1, or 0. CheckCommand: Invoke-IcingaCheckProcess Arguments: System.Collections.Hashtable StackTrace: in Exit-IcingaExecutePlugin, C:\Program Files\WindowsPowerShell\Modules\ icinga-powershell-framework\cache\framework_cache.psm1: line 26525 in , : line 1_

Comand inspect:
`'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' '-NoProfile' '-NoLogo' '-ExecutionPolicy' 'ByPass' '-C' 'try { Use-Icinga -Minimal; } catch { Write-Output '\''The Icinga PowerShell Framework is either not installed on the system or not configured properly. Please check https://icinga.com/docs/windows for further details'\''; Write-Output '\''Error:'\'' $($_.Exception.Message)Components:`r`n$( Get-Module -ListAvailable '\''icinga-powershell-*'\'' )`r`n'\''Module-Path:'\''`r`n$($Env:PSModulePath); exit 3; }; Exit-IcingaExecutePlugin -Command '\''Invoke-IcingaCheckProcess'\'' ' '-MemoryWarning' '60%' '-MemoryCritical' '70%' '-CPUWarning' '50%' '-CPUCritical' '60%' '-Process' '@('\''powershell'\'')' '-NoPerfData' '-ThresholdInterval' ''\''5m'\'''`

**Comment by LordHepipud** [comment]
The linked PR should resolve the issue, atleast in my test environment. Can you please verify this?

**Comment by drapiti** [comment]
> The linked PR should resolve the issue, atleast in my test environment. Can you please verify this?

Will do, post back soon.

**Comment by drapiti** [comment]
I can confirm the issue is fixed. I think there are some other cosmetic issues with the output. For example in the below output the page file usage is showing in % rather than in bytes or KiB. This occurs when I use a % as a threshold.
![image](https://user-images.githubusercontent.com/4235359/236542113-8c75efa7-0a15-4d75-912e-621da4c56f8e.png)
Also if I set for example a threshold of 30% for a process over the total cpu usage of the server then this output is a little confusing. As it is telling me 97% cpu usage of the total cpu usage of the server but this is not the percentage in use relative to the specific process. Here I want to know when the powerhell process is using more than 30% of the total cpu usage for example. The powershell process itself is not at 97%.
![image](https://user-images.githubusercontent.com/4235359/236544809-10f22882-a579-4a6a-9cc8-2d44a992b245.png)

**Comment by drapiti** [comment]
Occassionally throwing this error also, so maybe the % is not being correctly interpreted. This message comes and goes.
![image](https://user-images.githubusercontent.com/4235359/236551657-30c578e5-d0fa-401b-bacf-8ef7686b1ec5.png)
Working with same settings:
![image](https://user-images.githubusercontent.com/4235359/236552503-6d07a6ad-88b4-4444-8eaa-b098a337e0e7.png)

Variables used in this example are as follows:
![image](https://user-images.githubusercontent.com/4235359/236552080-2baf6626-3fb4-4aad-982e-9d21d59cb579.png)

**Comment by LordHepipud** [comment]
Thanks for testing.

For the CPU usage: The 97% value seems fine to me, as this indicates that one thread of your CPU is used by 97%. The value can go beyond 100%, as it will tell the user on how many cores are consumed by a single application or a pool of applications.

I need to have a look on that page file behavior. You are correct, this doesn't seem to be right.

**Comment by LordHepipud** [comment]
Can you please test the linked PR for the plugins? This should resolve the issue with the pagefile

**Comment by drapiti** [comment]
> Can you please test the linked PR for the plugins? This should resolve the issue with the pagefile
@LordHepipud, I am not sure if it is working as I am still getting a very large value followed by the percentage unit.
![image](https://github.com/Icinga/icinga-powershell-framework/assets/4235359/ed42e444-7930-4f2d-bb90-1842fe7a4905)

**Comment by LordHepipud** [comment]
Have you rebuild the plugin cache? You can do so by using

```powershell
Copy-IcingaFrameworkCacheTemplate
```

Afterwards you can execute the plugin again with a new shell and the changes should apply.

**Comment by drapiti** [comment]
> Have you rebuild the plugin cache? You can do so by using
> 
> ```powershell
> Copy-IcingaFrameworkCacheTemplate
> ```
> 
> Afterwards you can execute the plugin again with a new shell and the changes should apply.

Great yes looks better now re-published.
![image](https://github.com/Icinga/icinga-powershell-framework/assets/4235359/e3ae3813-6359-4b45-8332-6732a17a0cfa)

**Comment by drapiti** [comment]
Hi @LordHepipud just checking back on the process check, occassionally it goes into an unknown state:
![image](https://github.com/Icinga/icinga-powershell-framework/assets/4235359/65d17d7e-6007-453c-ba3f-b9433910387e)
this is using the updated fixes ecc. It does this on one iteration and then the next it will be ok.
