### ISSUE TITLE
Set-IcingaAgentServiceUser fails for parameter -user with format user@domain

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-framework#623]
Set-IcingaAgentServiceUser fails if the user is defined in the format user@domain, which is a [valid format](https://community.spiceworks.com/topic/2015276-logging-in-with-domain-username-or-username-domain-com-in-windows-environment).  
In this case the prefix '.\\' is added, which breaks the service:

![image](https://github.com/Icinga/icinga-powershell-framework/assets/34264690/aeccf5c1-d76f-40c6-b60e-c178de677ec8)

## Expected Behavior
```
Set-IcingaAgentServiceUser -User user@domain -SetPermission
[..]
[Notice]: Service User "user@domain" for service "icinga2" successfully updated
```

## Current Behavior
The '.\\'-Prefix is wrong in this case.
```
Set-IcingaAgentServiceUser -User user@domain -SetPermission
[..]
[Notice]: Service User ".\user@domain" for service "icinga2" successfully updated
```

## Possible Solution
Dont add the prefix '.\\' in case of the format user@domain.

## Your Environment
Framework: 1.10.1  
PS: 5.1

**Comment by LordHepipud** [comment]
```powershell
icinga> Set-IcingaServiceUser -User 'NT Authority\NetworkService'
[Notice]: Service User "NT Authority\NetworkService" for service "icinga2" successfully updated

icinga> Set-IcingaServiceUser -User 'NetworkService@NT Authority'
[Notice]: Service User "NT Authority\NetworkService" for service "icinga2" successfully updated

```
