### ISSUE TITLE
Using "icinga -DeveloperMode" causes CPU usage of 100%

### ISSUE THREAD

**Issue by Nayakum** [Icinga/icinga-powershell-framework#665]
## Expected Behavior
Using the built in Developer Mode should not cause a CPU usage of 100%.

## Current Behavior
When using the built in DeveloperMode via "icinga -DeveloperMode" on a server that is also actively running an Icinga agent and enabled in the central Icinga instance, a lot of PowerShell processes are started over time which are in turn causing a CPU usage of 100%. Since this does not go down, the server is effectively rendered unusable and needs to be hard reset.
If the host is disabled in Icinga while using the DeveloperMode, the issue does not happen. Enabling or disabling JEA has no effect whatsoever.

![grafik](https://github.com/Icinga/icinga-powershell-framework/assets/84782250/0bd50286-7d88-4f22-bd22-e700b59fd072)

![grafik](https://github.com/Icinga/icinga-powershell-framework/assets/84782250/ba38860f-00c5-4a40-b794-3f7ad5d9e51b)

## Steps to Reproduce (for bugs)

1. use e.g. "icinga -DeveloperMode { Invoke-IcingaCheckCPU }"
2. check the CPU usage in the task manager

## Context
Usually not an issue, it came up when following the official webinar to build our own plugins. The server only has two CPUs, maybe that's part of the issue. However, getting the server back up and running is somewhat difficult. I have to disable the host in Icinga and then restart it. Restarting while the host is still active in Icinga immediately causes the CPU usage to go to 100% again. After restarting the server, I can enable it in Icinga.

## Your Environment
**PowerShell version:**

![grafik](https://github.com/Icinga/icinga-powershell-framework/assets/84782250/88683230-7f86-4fa9-95ee-00c1f34cfb71)

**Operating System:**

![grafik](https://github.com/Icinga/icinga-powershell-framework/assets/84782250/139c1043-c7b0-459d-97a9-02e0bce93904)

**Installed IfW components:**

![grafik](https://github.com/Icinga/icinga-powershell-framework/assets/84782250/d2d86b10-4762-4911-8774-8b8302a5c2b5)

**Comment by LordHepipud** [comment]
Thank you for the issue. It is highly not recommended to use the developer mode on machines that are actively running Icinga checks on the background.

The reason for that is that all PowerShell cache files are deleted by the developer mode after the profiles are compiled. This means that every time you are running a PowerShell for Icinga for Windows in developer mode, that cache is reset and rebuilt by each plugin call in parallel. This will not only cause massive performance problems but can also corrupt the cache files in addition.

I would recommend a standalone Windows machine for this or disable the Icinga Agent during the development sessions, and start it again when finished.

**Comment by Nayakum** [comment]
Thanks for the headsup, I will keep this is mindfor further developing sessions. I'd recommend documenting this behaviour someplace, so that it users like me can find out what's going to happen to them. :D
That said, I'll close this issue it doesn't seem to be something that's actually a bug etc.
