### ISSUE TITLE
Install-Icinga uses wrong port to get parent certificate

### ISSUE THREAD

**Issue by Donien** [Icinga/icinga-powershell-framework#687]
# `Install-Icinga` uses the local node's port instead of the parent's port.

When running `Install-Icinga` the local node's port (**IfW-Port**) is used to connect to the defined parent.

E.g.
- IfW port: **5777**
- Parent Icinga port: **5665**

This results in the following command when running `Install-Icinga`:

```
C:\Program Files\ICINGA2\sbin\icinga2.exe pki request \
    --host icinga.localdomain \
    --port 5777 \
    --key C:\ProgramData\icinga2\var\lib\icinga2\certs\windows.key \
    --cert C:\ProgramData\icinga2\var\lib\icinga2\certs\windows.crt \
    --trustedcert C:\ProgramData\icinga2\var\lib\icinga2\certs\trusted-parent.crt \
    --ca C:\ProgramData\icinga2\var\lib\icinga2\certs\ca.crt
```

This command however fails because the parent's port is **not** 5777 but 5665.

---

Actual (full) command run:
<details>
  <summary>Expand</summary>

```
Install-Icinga -InstallCommand "
{
  'IfW-CustomZones': {
    'Values': [
      'director-global',
      'global-templates'
    ]
  },
  'IfW-GlobalZones': {
    'Selection': '3'
  },
  'IfW-InstallAgent': {
    'Selection': '1'
  },
  'IfW-Port': {
    'Values': [
      '5777'
    ]
  },
  'IfW-ParentNodes': {
    'Values': [
      'main'
    ]
  },
  'IfW-ParentZone': {
    'Values': [
      'main'
    ]
  },
  'IfW-ParentAddress': {
    'Values': {
      'main': [
        '[icinga.localdomain]:5665'
      ]
    }
  },
  'IfW-InstallPlugins': {
    'Selection': '1'
  },
  'IfW-Connection': {
    'Selection': '2'
  },
  'IfW-InstallService': {
    'Selection': '1'
  },
  'IfW-Certificate': {
    'Selection': '1'
  },
  'IfW-CAServer': {
    'Values': [
      'icinga.localdomain'
    ]
  },
  'IfW-InstallJEAProfile': {
    'Selection': '2'
  },
  'IfW-Hostname': {
    'Selection': '0'
  }
}
"
```

</details>

Command run (with relevant parts):

```
Install-Icinga -InstallCommand "
{
  ...
  'IfW-Port': {
    'Values': [
      '5777'
    ]
  },
  'IfW-ParentNodes': {
    'Values': [
      'main'
    ]
  },
  'IfW-ParentZone': {
    'Values': [
      'main'
    ]
  },
  'IfW-ParentAddress': {
    'Values': {
      'main': [
        '[icinga.localdomain]:5665'
      ]
    }
  },
  ...
}
"
```

---

I think setting **5665** as the default to connect to the parent should be the way to go unless another port is specified for the parent endpoint itself (**[icinga.localdomain]:5665**).

The local port on which the Windows host should listen should not affect the port used to connect to the parent.

**Comment by LordHepipud** [comment]
Thank you for your issue. Can you please explain why the local Windows port should be different to the parent nodes Icinga port?

This is in general not best practice, as the Icinga environment should listen on the same port. However, forcing 5665 to be used every time is not a suitable option, as there are environments where this is not the default port and therefore all those installations would fail.

I need to have a deeper look into this, as a simple change could break current environments in case the behavior changes. In addition, I'm not sure if the described behavior is wrong or correct 🤔
