### ISSUE TITLE
"Install-IcingaComponent -Name service" tries to update non existing service

### ISSUE THREAD

**Issue by Byolock** [Icinga/icinga-powershell-framework#717]
I am trying to install the framework service on a windows 10 machine using `Install-IcingaComponent -Name service -Force` , but I do get the following error message every time :

```
Failed to update config for Icinga PowerShell Service: [SC] OpenService FEHLER 1060:
Der angegebene Dienst ist kein installierter Dienst.
In C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\cache\framework_cache.psm1:2657 Zeichen:13
+             throw ([string]::Format('Failed to update config for Icin ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to updat...rter Dienst.
:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to update config for Icinga PowerShell Service: [SC] OpenService FEHLER 1060:
Der angegebene Dienst ist kein installierter Dienst.
```

I tried to understand what the specified part of the code in the framework_cache.psm1 file does, and apparently it tries to detect if the service is already present or not and then either installs the service or updates the configuration. In my case the service is not present (neither found with 'get-service' in PS, or displayed in the services menu of windows), but is detected as present, therefore the code to update the service configuration fails and I am unable to install the service. 
Unfourtanetly I don't quite understand how it is determining if the service is present or not. 

I would appreciate it if someone could help me to understand why the framework assumes the service is installed although its not.

**Comment by LordHepipud** [comment]
Hello,

thanks for the issue. That is fixed with #714 and will ship with v1.12.1 shortly.
