### ISSUE TITLE
IfW Powershell Framework - JEA Service orphaned 

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icinga-powershell-framework#734]
## Issue Description
Under some circumstances it seems possible that the main icinga2 service get's stuck (crashed but in service tab still listed as running)and therefore the JEA Service keeps on running.
There should be a solution for a graceful restart/graceful kill of both services to have them running in dependency again.

Because 
SC failure icinga2.exe reset= 0 actions= restart/0/restart/0/restart/0 
doesn't cover this edge case.

##
ref/NC/816257

**Comment by LordHepipud** [comment]
Side note: It's the `icingapowershell` service and not the `icinga2` service

**Comment by Wintermute2k6** [comment]
apology, my failure .. thanks for correcting

**Comment by Wintermute2k6** [comment]
ref/NC/816257 Addition:

Under certain circumstances the Icinga PowerShell service may crash. This crash leaves an orphaned JEA session behind, which causes the service to terminate itself after a few milliseconds when restarted automatically/manually.
Since the service is not active in this situation, the monitoring raises a critical alarm in the service check.
The service should be allowed to run in parallel and only actively attempt to establish a new JEA session if the old, orphaned process disappears for some reason.
