### ISSUE TITLE
Invoke-IcingaCheckDiskHealth plugin returns empty values ​​for some performance metrics

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [Icinga/icinga-powershell-framework#746]
Hello

Sometimes the Invoke-IcingaCheckDiskHealth plugin returns empty values ​​for some important performance metrics
The result is an incorrect comparison operation. And the plugin reports that 0 is greater than 4.
This causes an unwanted change in the plugin status in CRITICAL
I will give an example in the screenshots below

![изображение](https://github.com/Icinga/icinga-powershell-plugins/assets/17614847/d2203c77-28a1-4be9-8895-818679b96de4)

![изображение](https://github.com/Icinga/icinga-powershell-plugins/assets/17614847/f9187d4c-ff9e-44fb-9fc1-0b2a6fa7c2ca)

![изображение](https://github.com/Icinga/icinga-powershell-plugins/assets/17614847/299aa259-6662-42a5-b403-71ecb8d06c6e)

**Comment by LordHepipud** [comment]
Thank you for the report. Could you please test the linked PR of the Framework? This should resolve the issue to at least report proper values.
