### ISSUE TITLE
Check installed .NET Framework version on Host before Agent installation

### ISSUE THREAD

**Issue by LordHepipud** [Icinga/icinga-powershell-framework#76]
For installing the Icinga 2 Agent MSI package, we will require .NET Framework version 4.6 or higher. In case the package is not intsalled, the installation will fail without a notification. To get to know this error, the user will have to start the MSI installation manually on the UI.

## Expected Behavior

We should add a test for installed .NET Framework versions prior of installing the Agent and return a proper message and error handling if the requirements are not fullfilled

## Current Behavior

The installation will fail without proper notification of the user

## Possible Solution

Add test function for installed .NET Framework versions

**Comment by K0nne** [comment]
Here is our approach on this:

```
# check based on: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed
if ((Get-ItemProperty "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full").Release -lt 393295)
...
```

**Comment by LordHepipud** [comment]
Thank you for the input - I came to the same conclusion using the registry to fetch the proper versions. Seems to be the only valid and cross-plattform solution.
