### ISSUE TITLE
Some check packages try to read inaccessible security eventlog

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-framework#81]
Yesterday in the evening I stumbled upon a new permission problem, which affects all of my perfcounter checks, which I wanted to rollout today for MSSQL :~ I don't know where its coming from, because the confguration worked before. Something has changed.

I placed the latest packages (framework & plugins) here and the output is as following:

```
Exception calling "SourceExists" with "1" argument(s): "The source was not found, but some or all event logs could not
be searched.  Inaccessible logs: Security."

At C:\Program 

Files\WindowsPowerShell\Modules\icinga-powershell-framework\lib\core\logging\Register-IcingaEventLog.psm1:3 char:5

+     $Registered = [System.Diagnostics.EventLog]::SourceExists(

+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException

    + FullyQualifiedErrorId : SecurityException

 

New-EventLog : Access is denied. Try running the command again in a session that has been opened with elevated user 

rights (that is, Run as Administrator).

At C:\Program 

Files\WindowsPowerShell\Modules\icinga-powershell-framework\lib\core\logging\Register-IcingaEventLog.psm1:11 char:5

+     New-EventLog -LogName Application -Source 'Icinga for Windows';

+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidOperation: (:) [New-EventLog], Exception

    + FullyQualifiedErrorId : AccessIsDenied,​Microsoft.PowerShell.Commands.NewEventLogCommand
```

**[OK] Check package "Performance Counter""**

Its the same with the check package "CPU Load".

The strange thing is: the checks are working. I'm getting graphs and perfdata. I'm not sure what's up with the eventlog here, because I want to monitor perfcounter.

_Originally posted by @K0nne in https://github.com/Icinga/icinga-powershell-framework/issues/80#issuecomment-664847055_

**Comment by LordHepipud** [comment]
A great - now we both had the same idea 👍 

Also see #82

**Comment by K0nne** [comment]
On the affected system I executed `use-icinga` in an admin powershell and the errors in the plugin output were gone.

**Comment by LordHepipud** [comment]
A fix is inside the master now. If you got another system with identical problems, maybe you can try the latest Framework master

**Comment by K0nne** [comment]
I put the new packages and the affected checks to another system.
Now there's another error:


```
New-EventLog : Access is denied. Try running the command again in a session that has been opened with elevated user
rights (that is, Run as Administrator).

At C:\Program 

Files\WindowsPowerShell\Modules\icinga-powershell-framework\lib\core\logging\Register-IcingaEventLog.psm1:21 char:5

+     New-EventLog -LogName Application -Source 'Icinga for Windows';

+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidOperation: (:) [New-EventLog], Exception

    + FullyQualifiedErrorId : AccessIsDenied,​Microsoft.PowerShell.Commands.NewEventLogCommand

 

[OK] Check package "Performance Counter"
```

**Comment by LordHepipud** [comment]
Well - ok. I get the point then.

So basically we have three options here:

* Handle the exception and ignore it - making it impossible for the user to determine if there is a problem (because we can't print it anywhere)
* Throw an Icinga Exception and return an "Unknown" check result, informing the user that the Framework is not properly installed and he has to call `Use-Icinga` once on the target machine with administrative privileges
* Add a health check plugin to the plugin collection to check for events like this - together with ignoring the exception. Which will how ever require the user to add the health check to every system

What do you think?

**Comment by K0nne** [comment]
I am thinking about adding the `Use-Icinga` command to our install-script, which could lead to the 2nd option. I need to talk with my collegues about this. I will report back next week.

**Comment by K0nne** [comment]
Option #2 whould be ok.

**Comment by LordHepipud** [comment]
Thanks!
